// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.

package relaytelemetry

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// Cross-implementation test vectors for ADR-0021/ADR-0048/ADR-0045's
// telemetry signing input.
//
// The Go control server and the Rust relay each build the same 136-byte
// message independently — this file, and `bins/karst-relay/src/telemetry.rs`'s
// signing_input. A field reordered, a width changed from 8 bytes to 4, or a
// byte order flipped on either side would still let every other test pass:
// signingInput is only ever exercised against itself, and a self-consistent
// implementation agrees with itself no matter what it does. A vector generated
// by one side and checked by the other is the only thing that would fail.
//
// The signature itself is deliberately not vectored, the same reason
// KARST-CONTROL's vectors do not pin one: ML-DSA-87 signing is hedged
// (ponor-v1.md §5.5), so no signature over these bytes is reproducible
// material. What has to agree, and can be pinned, is the bytes signed over.
//
// Cases 0-2 predate ADR-0048 and are left with has_location=false,
// lat_e7=lon_e7=0 precisely so their first 80 bytes stay byte-identical to
// what was committed before — a regression check that the location fields
// were appended, not spliced in. Cases 3-5 (added by ADR-0048) cover no
// location, a (0,0) location, and the ±90/±180 boundary at the E7 scale.
// Cases 0-5 all leave §4a's four RTT bucket fields zero for the same
// byte-identical-prefix reason; case 6 (added by ADR-0045 §4a) is the one
// that exercises them, with distinct, non-zero values in each so a bucket
// swapped with its neighbor would still fail.
//
// Regenerate with:  UPDATE_VECTORS=1 go test ./management/internals/karst/relaytelemetry/ -run Vectors

type vectorFile struct {
	Spec  string             `json:"spec"`
	Note  string             `json:"note"`
	Cases []signingInputCase `json:"signing_input"`
}

type signingInputCase struct {
	RelayID       string `json:"relay_id"`
	Timestamp     int64  `json:"timestamp"`
	LocalClients  int    `json:"local_clients"`
	MeshPeers     int    `json:"mesh_peers"`
	RemoteClients int    `json:"remote_clients"`
	BytesTotal    int64  `json:"bytes_total"`
	UptimeSecs    int64  `json:"uptime_secs"`
	HasLocation   bool   `json:"has_location"`
	LatE7         int64  `json:"lat_e7"`
	LonE7         int64  `json:"lon_e7"`
	RTTUnder20ms  int64  `json:"rtt_under_20ms"`
	RTT20To50ms   int64  `json:"rtt_20_to_50ms"`
	RTT50To100ms  int64  `json:"rtt_50_to_100ms"`
	RTTOver100ms  int64  `json:"rtt_over_100ms"`
	Expected      string `json:"expected"`
}

func pattern(n int, seed byte) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = seed + byte(i)
	}
	return out
}

func vectorsPath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate this source file")
	}
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"spec", "vectors", "relay-telemetry-v1.json")
}

func TestVectors(t *testing.T) {
	got := vectorFile{
		Spec: "ADR-0021 relay telemetry signing input",
		Note: "Cross-implementation vectors for the 136-byte message " +
			"ADR-0021/ADR-0048/ADR-0045's telemetry report is signed over: " +
			"relay_id followed by thirteen big-endian u64 fields (the " +
			"original six, plus has_location/lat_e7/lon_e7 added by " +
			"ADR-0048, plus §4a's four RTT histogram buckets). Not the " +
			"signature itself — ML-DSA-87 signing is hedged, so no " +
			"signature is reproducible vector material — only the bytes " +
			"signed over. " +
			"Generated by server/management/internals/karst/relaytelemetry/vectors_test.go.",
	}

	for _, tc := range []struct {
		relayIDSeed   byte
		timestamp     int64
		localClients  int
		meshPeers     int
		remoteClients int
		bytesTotal    int64
		uptimeSecs    int64
		hasLocation   bool
		latE7         int64
		lonE7         int64
		rttUnder20ms  int64
		rtt20To50ms   int64
		rtt50To100ms  int64
		rttOver100ms  int64
	}{
		{relayIDSeed: 0x00},
		{relayIDSeed: 0x11, timestamp: 1_700_000_000, localClients: 3, meshPeers: 1, remoteClients: 7, bytesTotal: 1_000, uptimeSecs: 60},
		// Large values in every field, so a truncation to 32 bits anywhere
		// in either implementation shows up as a vector mismatch rather
		// than as a report that merely looks a little off in production.
		{relayIDSeed: 0x22, timestamp: 9_223_372_036_854_775_807, localClients: 4_000_000_000, meshPeers: 4_000_000_000, remoteClients: 4_000_000_000, bytesTotal: 9_223_372_036_854_775_807, uptimeSecs: 4_000_000_000},
		// ADR-0048: has_location=false with otherwise-populated fields —
		// confirms the flag, not merely zeroed coordinates, is what signals
		// absence.
		{relayIDSeed: 0x33, timestamp: 1_700_000_000, localClients: 5, meshPeers: 2, remoteClients: 10, bytesTotal: 2_000, uptimeSecs: 120},
		// A location at (0, 0) — the one coordinate value that could be
		// mistaken for "unset" if the flag were ever dropped.
		{relayIDSeed: 0x44, timestamp: 1_700_000_000, localClients: 1, meshPeers: 1, remoteClients: 1, bytesTotal: 1, uptimeSecs: 1, hasLocation: true},
		// The ±90/±180 boundary at the E7 scale, so a sign-extension or
		// truncation bug on either side shows up here rather than in
		// production at the literal edge of the Earth.
		{relayIDSeed: 0x55, timestamp: 1_700_000_000, localClients: 9, meshPeers: 9, remoteClients: 9, bytesTotal: 9, uptimeSecs: 9, hasLocation: true, latE7: -900_000_000, lonE7: -1_800_000_000},
		// ADR-0045 §4a: four distinct, non-zero bucket counts, so a bucket
		// swapped with its neighbor — or truncated at 32 bits, like the
		// other fields above check for — shows up as a vector mismatch.
		{relayIDSeed: 0x66, timestamp: 1_700_000_000, localClients: 100, rttUnder20ms: 40, rtt20To50ms: 30, rtt50To100ms: 20, rttOver100ms: 10},
	} {
		relayID := pattern(32, tc.relayIDSeed)
		// req.RelayID is deliberately left unset: signingInput takes the
		// decoded relay id as its own argument and never reads the field.
		req := report{
			Timestamp:     tc.timestamp,
			LocalClients:  tc.localClients,
			MeshPeers:     tc.meshPeers,
			RemoteClients: tc.remoteClients,
			BytesTotal:    tc.bytesTotal,
			UptimeSecs:    tc.uptimeSecs,
			HasLocation:   tc.hasLocation,
			LatE7:         tc.latE7,
			LonE7:         tc.lonE7,
			RTTUnder20ms:  tc.rttUnder20ms,
			RTT20To50ms:   tc.rtt20To50ms,
			RTT50To100ms:  tc.rtt50To100ms,
			RTTOver100ms:  tc.rttOver100ms,
		}
		got.Cases = append(got.Cases, signingInputCase{
			RelayID:       hex.EncodeToString(relayID),
			Timestamp:     tc.timestamp,
			LocalClients:  tc.localClients,
			MeshPeers:     tc.meshPeers,
			RemoteClients: tc.remoteClients,
			BytesTotal:    tc.bytesTotal,
			UptimeSecs:    tc.uptimeSecs,
			HasLocation:   tc.hasLocation,
			LatE7:         tc.latE7,
			LonE7:         tc.lonE7,
			RTTUnder20ms:  tc.rttUnder20ms,
			RTT20To50ms:   tc.rtt20To50ms,
			RTT50To100ms:  tc.rtt50To100ms,
			RTTOver100ms:  tc.rttOver100ms,
			Expected:      hex.EncodeToString(signingInput(relayID, req)),
		})
	}

	encoded, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	encoded = append(encoded, '\n')

	path := vectorsPath(t)
	if os.Getenv("UPDATE_VECTORS") != "" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, encoded, 0o644); err != nil {
			t.Fatalf("write: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read vectors (regenerate with UPDATE_VECTORS=1): %v", err)
	}
	if string(want) != string(encoded) {
		t.Fatal("generated vectors differ from the committed file. " +
			"If this is an intended protocol change, regenerate with " +
			"UPDATE_VECTORS=1 and expect the Rust side to fail until it is updated too.")
	}
}
