// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.

package relaytelemetry

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// Cross-implementation test vectors for ADR-0021's telemetry signing input.
//
// The Go control server and the Rust relay each build the same 80-byte
// message independently — this file, and `bins/karst-relay/src/telemetry.rs`'s
// signing_input. A field reordered, a width changed from 8 bytes to 4, or a
// byte order flipped on either side would still let every other test pass:
// signingInput is only ever exercised against itself, and a self-consistent
// implementation agrees with itself no matter what it does. A vector generated
// by one side and checked by the other is the only thing that would fail.
//
// The signature itself is deliberately not vectored, the same reason
// KARST-CONTROL's vectors do not pin one: ML-DSA-87 signing is hedged
// (ponor-v1.md §5.5), so no signature over these bytes is reproducible
// material. What has to agree, and can be pinned, is the bytes signed over.
//
// Regenerate with:  UPDATE_VECTORS=1 go test ./management/internals/karst/relaytelemetry/ -run Vectors

type vectorFile struct {
	Spec  string             `json:"spec"`
	Note  string             `json:"note"`
	Cases []signingInputCase `json:"signing_input"`
}

type signingInputCase struct {
	RelayID       string `json:"relay_id"`
	Timestamp     int64  `json:"timestamp"`
	LocalClients  int    `json:"local_clients"`
	MeshPeers     int    `json:"mesh_peers"`
	RemoteClients int    `json:"remote_clients"`
	BytesTotal    int64  `json:"bytes_total"`
	UptimeSecs    int64  `json:"uptime_secs"`
	Expected      string `json:"expected"`
}

func pattern(n int, seed byte) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = seed + byte(i)
	}
	return out
}

func vectorsPath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate this source file")
	}
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "..",
		"spec", "vectors", "relay-telemetry-v1.json")
}

func TestVectors(t *testing.T) {
	got := vectorFile{
		Spec: "ADR-0021 relay telemetry signing input",
		Note: "Cross-implementation vectors for the 80-byte message ADR-0021's " +
			"telemetry report is signed over: relay_id followed by six " +
			"big-endian u64 fields. Not the signature itself — ML-DSA-87 " +
			"signing is hedged, so no signature is reproducible vector " +
			"material — only the bytes signed over. " +
			"Generated by server/management/internals/karst/relaytelemetry/vectors_test.go.",
	}

	for _, tc := range []struct {
		relayIDSeed   byte
		timestamp     int64
		localClients  int
		meshPeers     int
		remoteClients int
		bytesTotal    int64
		uptimeSecs    int64
	}{
		{0x00, 0, 0, 0, 0, 0, 0},
		{0x11, 1_700_000_000, 3, 1, 7, 1_000, 60},
		// Large values in every field, so a truncation to 32 bits anywhere
		// in either implementation shows up as a vector mismatch rather
		// than as a report that merely looks a little off in production.
		{0x22, 9_223_372_036_854_775_807, 4_000_000_000, 4_000_000_000, 4_000_000_000, 9_223_372_036_854_775_807, 4_000_000_000},
	} {
		relayID := pattern(32, tc.relayIDSeed)
		// req.RelayID is deliberately left unset: signingInput takes the
		// decoded relay id as its own argument and never reads the field.
		req := report{
			Timestamp:     tc.timestamp,
			LocalClients:  tc.localClients,
			MeshPeers:     tc.meshPeers,
			RemoteClients: tc.remoteClients,
			BytesTotal:    tc.bytesTotal,
			UptimeSecs:    tc.uptimeSecs,
		}
		got.Cases = append(got.Cases, signingInputCase{
			RelayID:       hex.EncodeToString(relayID),
			Timestamp:     tc.timestamp,
			LocalClients:  tc.localClients,
			MeshPeers:     tc.meshPeers,
			RemoteClients: tc.remoteClients,
			BytesTotal:    tc.bytesTotal,
			UptimeSecs:    tc.uptimeSecs,
			Expected:      hex.EncodeToString(signingInput(relayID, req)),
		})
	}

	encoded, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	encoded = append(encoded, '\n')

	path := vectorsPath(t)
	if os.Getenv("UPDATE_VECTORS") != "" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, encoded, 0o644); err != nil {
			t.Fatalf("write: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read vectors (regenerate with UPDATE_VECTORS=1): %v", err)
	}
	if string(want) != string(encoded) {
		t.Fatal("generated vectors differ from the committed file. " +
			"If this is an intended protocol change, regenerate with " +
			"UPDATE_VECTORS=1 and expect the Rust side to fail until it is updated too.")
	}
}
