// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright the Karst contributors.

//! BEDROCK v1 cross-implementation vectors.
//!
//! `spec/vectors/bedrock-v1.json` is generated by the Go server
//! (`server/management/internals/karst/bedrock/vectors_test.go`) and consumed
//! here. A disagreement between the two implementations shows up as a failure
//! in this file rather than as a node that silently refuses every peer.
//!
//! The `rejected` cases carry as much weight as the valid ones: a verifier that
//! accepts everything passes every positive vector in the file.

#![allow(
    clippy::panic,
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::doc_markdown
)]

use std::path::PathBuf;

use karst_bedrock::{
    anchor_body, authority_list_body, chain_hash, decode_log, disable_body, genesis_body,
    node_revoke_body, node_sign_body, quorum_change_body, verify_log, Op,
};
use karst_crypto::sign::{
    verify_authority, verify_root, AuthorityKey, RootKey, AUTHORITY_CONTEXT, ROOT_CONTEXT,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct VectorFile {
    spec: String,
    cases: Cases,
}

#[derive(Deserialize)]
struct Cases {
    root_sign: Vec<RootSignCase>,
    authority_sign: Vec<AuthSignCase>,
    chain_hash: Vec<ChainHashCase>,
    bodies: Vec<BodyCase>,
    logs: Vec<LogCase>,
    rejected: Vec<RejectedCase>,
}

#[derive(Deserialize)]
struct RootSignCase {
    seed: String,
    public_key: String,
    context: String,
    message: String,
    signature: String,
}

#[derive(Deserialize)]
struct AuthSignCase {
    seed: String,
    public_key: String,
    context: String,
    message: String,
    signature: String,
}

#[derive(Deserialize)]
struct ChainHashCase {
    prev: String,
    seq: u64,
    time: i64,
    op: String,
    body: String,
    hash: String,
}

#[derive(Deserialize)]
struct BodyCase {
    op: String,
    note: String,
    encoding: String,
}

#[derive(Deserialize)]
struct LogCase {
    name: String,
    encoded: String,
    head: String,
    head_seq: u64,
    zone: String,
    quorum: u32,
    coverage: Vec<CoverageCase>,
}

#[derive(Deserialize)]
struct CoverageCase {
    handle: String,
    kem_public_key: String,
    dh_public_key: String,
    at: i64,
    covered: bool,
}

#[derive(Deserialize)]
struct RejectedCase {
    name: String,
    why: String,
    encoded: String,
}

fn load() -> VectorFile {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../spec/vectors/bedrock-v1.json")
        .canonicalize()
        .expect("locate spec/vectors/bedrock-v1.json");
    let raw = std::fs::read_to_string(&path).expect("read vectors");
    serde_json::from_str(&raw).expect("parse vectors")
}

fn unhex(s: &str) -> Vec<u8> {
    hex::decode(s).expect("hex")
}

#[test]
fn vector_file_is_the_expected_spec() {
    assert_eq!(load().spec, "BEDROCK v1");
}

/// The signature layer. These pin **exact bytes**, not merely that verification
/// succeeds: ADR-0014 makes Bedrock signing deterministic precisely so that
/// circl and RustCrypto can be held to the same output. A vector that only
/// asserted "this verifies" would still pass if one side signed the wrong
/// message under the right key.
#[test]
fn root_signatures_match_the_go_implementation() {
    for (i, c) in load().cases.root_sign.iter().enumerate() {
        assert_eq!(
            c.context.as_bytes(),
            ROOT_CONTEXT,
            "case {i}: context string drifted"
        );

        let key = RootKey::from_seed(&unhex(&c.seed)).expect("expand root key");
        assert_eq!(
            key.public_key(),
            unhex(&c.public_key),
            "case {i}: the same seed yields a different public key"
        );

        let msg = unhex(&c.message);
        let expected = unhex(&c.signature);

        assert!(
            verify_root(&unhex(&c.public_key), &msg, &expected),
            "case {i}: Rust cannot verify a signature Go produced"
        );
        assert_eq!(
            key.sign(&msg).expect("sign"),
            expected,
            "case {i}: deterministic signing produced different bytes from Go"
        );
    }
}

#[test]
fn authority_signatures_match_the_go_implementation() {
    for (i, c) in load().cases.authority_sign.iter().enumerate() {
        assert_eq!(
            c.context.as_bytes(),
            AUTHORITY_CONTEXT,
            "case {i}: context string drifted"
        );

        let key = AuthorityKey::from_seed(&unhex(&c.seed)).expect("expand authority key");
        assert_eq!(
            key.public_key(),
            unhex(&c.public_key),
            "case {i}: the same seed yields a different public key"
        );

        let msg = unhex(&c.message);
        let expected = unhex(&c.signature);

        assert!(
            verify_authority(&unhex(&c.public_key), &msg, &expected),
            "case {i}: Rust cannot verify a signature Go produced"
        );
        assert_eq!(
            key.sign(&msg).expect("sign"),
            expected,
            "case {i}: deterministic signing produced different bytes from Go"
        );
    }
}

/// The chain construction. A disagreement here makes every signature in every
/// log fail, with no other symptom.
#[test]
fn chain_hashes_match_the_go_implementation() {
    for (i, c) in load().cases.chain_hash.iter().enumerate() {
        let op = Op::parse(&c.op).unwrap_or_else(|| panic!("case {i}: unknown op {}", c.op));
        assert_eq!(
            chain_hash(&unhex(&c.prev), c.seq, c.time, op, &unhex(&c.body)),
            unhex(&c.hash),
            "case {i}: chain hash construction drifted"
        );
    }
}

/// Body layouts — spec §3.4. A disagreement here is a signature failure on
/// every entry of that type.
#[test]
fn body_encodings_match_the_go_implementation() {
    let file = load();
    // Each body is parsed and rebuilt: if either the layout or the parser
    // drifted, the rebuilt bytes stop matching what Go emitted.
    assert!(
        !file.cases.bodies.is_empty(),
        "no body cases in the vectors"
    );
    for c in &file.cases.bodies {
        let raw = unhex(&c.encoding);
        let rebuilt = match c.op.as_str() {
            "genesis" => {
                let b = karst_bedrock::parse_genesis(&raw).expect("genesis");
                genesis_body(&b.zone, &b.roots, b.k, &b.authorities, b.q)
            }
            "authority-list" => {
                let b = karst_bedrock::parse_authority_list(&raw).expect("authority-list");
                authority_list_body(&b.authorities, b.q)
            }
            "node-sign" => {
                let b = karst_bedrock::parse_node_sign(&raw).expect("node-sign");
                node_sign_body(
                    &b.handle,
                    &b.identity_key,
                    &b.kem_public_key,
                    &b.dh_public_key,
                    b.not_before,
                    b.expiry,
                )
            }
            "node-revoke" => {
                let b = karst_bedrock::parse_node_revoke(&raw).expect("node-revoke");
                node_revoke_body(&b.handle, &b.reason, b.effective)
            }
            "quorum-change" => {
                quorum_change_body(karst_bedrock::parse_quorum_change(&raw).expect("quorum"))
            }
            "anchor" => {
                let b = karst_bedrock::parse_anchor(&raw).expect("anchor");
                anchor_body(&b.audit_head, b.audit_seq)
            }
            "disable" => disable_body(&karst_bedrock::parse_disable(&raw).expect("disable")),
            other => panic!("unknown op {other} in bodies"),
        };
        assert_eq!(
            rebuilt, raw,
            "body layout drifted for op {} ({})",
            c.op, c.note
        );
    }
}

/// Length prefixing, pinned as two cases that would be byte-identical without
/// it. Two implementations that both omitted the prefixes would agree with each
/// other and disagree with this file.
#[test]
fn adjacent_fields_are_length_prefixed() {
    let file = load();
    let pair: Vec<&BodyCase> = file
        .cases
        .bodies
        .iter()
        .filter(|c| c.note.starts_with("length prefixing"))
        .collect();
    assert_eq!(pair.len(), 2, "the length-prefixing pair is missing");
    assert_ne!(
        pair[0].encoding, pair[1].encoding,
        "ab|c and a|bc encode identically: fields are not length-prefixed"
    );
}

/// A whole log, decoded and verified, with the coverage decisions that follow
/// from it. This is the end-to-end agreement check.
#[test]
fn logs_verify_to_the_same_state_as_go() {
    for c in &load().cases.logs {
        let entries = decode_log(&unhex(&c.encoded))
            .unwrap_or_else(|e| panic!("{}: decode failed: {e}", c.name));
        let st = verify_log(&entries)
            .unwrap_or_else(|e| panic!("{}: Go accepted this log, Rust refused it: {e}", c.name));

        assert_eq!(st.head, unhex(&c.head), "{}: head hash differs", c.name);
        assert_eq!(st.head_seq, c.head_seq, "{}: head sequence differs", c.name);
        assert_eq!(st.zone, c.zone, "{}: zone differs", c.name);
        assert_eq!(st.q, c.quorum, "{}: quorum differs", c.name);

        for (i, cov) in c.coverage.iter().enumerate() {
            let kem = unhex(&cov.kem_public_key);
            let dh = unhex(&cov.dh_public_key);
            assert_eq!(
                st.is_covered(
                    &cov.handle,
                    karst_bedrock::PeerKeys {
                        kem_public_key: &kem,
                        dh_public_key: &dh,
                    },
                    cov.at
                ),
                cov.covered,
                "{}: coverage case {i} ({} at {}) differs from Go",
                c.name,
                cov.handle,
                cov.at
            );
        }
    }
}

/// Every log the Go implementation refuses, this one must refuse too.
///
/// This is the half of the vector file that a broken verifier fails. Accepting
/// one of these means the node would peer with something Bedrock exists to
/// exclude.
#[test]
fn rejected_logs_are_rejected_here_too() {
    for c in &load().cases.rejected {
        let raw = unhex(&c.encoded);
        // Rejection may happen at either stage: an unknown op is caught while
        // decoding, everything else while verifying. Both are refusals.
        let accepted = match decode_log(&raw) {
            Err(_) => false,
            Ok(entries) => verify_log(&entries).is_ok(),
        };
        assert!(
            !accepted,
            "{}: accepted a log that must be refused ({})",
            c.name, c.why
        );
    }
}
