// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.

import { AxeBuilder } from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
for (const route of ["devices", "download", "access", "sessions"]) test(`${route} is accessible`, async ({ page }) => { await page.goto(`/#/${route}`); expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]); });
test("member can add, rename, and revoke a device using the keyboard", async ({ page }) => { await page.goto("/#/devices"); await page.getByRole("button", { name: "Add a device" }).press("Enter"); await expect(page.getByRole("status")).toContainText("[control] setup_key"); await expect(page.getByRole("status")).toContainText("start karstd"); await page.getByRole("button", { name: "Rename" }).first().press("Enter"); await page.getByLabel("New device name").fill("renamed laptop"); await page.getByRole("button", { name: "Save name" }).press("Enter"); await expect(page.getByRole("status")).toContainText("renamed"); page.on("dialog", (dialog) => dialog.accept()); await page.getByRole("button", { name: "Revoke" }).press("Enter"); await expect(page.getByRole("status")).toContainText("revoked"); });
test("download lists every build for the platform with its checksum", async ({ page }) => { await page.goto("/#/download"); const rows = page.getByRole("row").filter({ hasText: /karst-client/ }); await expect(rows).toHaveCount(4); await expect(page.getByRole("cell", { name: "arm64", exact: true }).first()).toBeVisible(); await expect(page.getByRole("link", { name: /karst-client_0\.1\.0-1_amd64\.deb/ })).toBeVisible(); await expect(page.getByText(/sha256sum/)).toBeVisible(); });
test("a platform Karst does not build for is not offered one", async ({ page }) => { await page.goto("/#/download"); await expect(page.getByText(/\.msi/)).toHaveCount(0); });
