// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.
//
// Karst control-channel envelope and handshake — see ADR-0011.
//
// This is a *separate file* from management.proto on purpose. Upstream's proto
// stays byte-identical to the fork point, so a cherry-picked security fix
// applies without conflict. Everything Karst adds lives here.
//
// It replaces NetBird's EncryptedMessage, which fuses three roles into one
// X25519 key — authentication handle, primary index, and transport encryption
// key. Karst's identity is ML-DSA-65 plus a static ML-KEM-768 key and has no
// such object, so the envelope names an opaque handle and carries the
// cryptography separately.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: karst_control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KarstLoginRequest registers a node or logs an existing one back in. It is
// sent inside a KarstEnvelope, so it is already authenticated by the time the
// server decodes it — the ML-DSA signature over the handshake transcript
// verified before the channel existed.
type KarstLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Pre-shared auth key. Optional once the node is registered.
	SetupKey string `protobuf:"bytes,1,opt,name=setup_key,json=setupKey,proto3" json:"setup_key,omitempty"`
	// Must be present: the business layer derives the peer's name and DNS label
	// from the hostname and refuses a login without it.
	Meta      *PeerSystemMeta `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	DnsLabels []string        `protobuf:"bytes,3,rep,name=dns_labels,json=dnsLabels,proto3" json:"dns_labels,omitempty"`
	// The node's PHREATIC data-plane keys. A Karst node holds three long-term
	// keypairs (phreatic-v1.md §4): the ML-DSA-65 identity, which authenticates
	// this control channel and is presented in ChannelInit, plus these two,
	// which PHREATIC actually uses. The identity key is deliberately *not* used
	// by PHREATIC.
	//
	// They are registered here because peers cannot handshake without them:
	// "A node MUST know, for every peer it may communicate with, that peer's
	// peer_id_hint, S_pk, D_pk and current per-pair PSK. These are distributed
	// in the netmap."
	KemPublicKey []byte `protobuf:"bytes,4,opt,name=kem_public_key,json=kemPublicKey,proto3" json:"kem_public_key,omitempty"` // Static KEM S — ML-KEM-768, 1184 B
	DhPublicKey  []byte `protobuf:"bytes,5,opt,name=dh_public_key,json=dhPublicKey,proto3" json:"dh_public_key,omitempty"`    // Static DH D — X25519, 32 B
	// OIDC ID token, for interactive registration (PLAN.md §4.2 step 2).
	//
	// An alternative to setup_key, not an addition: a node presents one or the
	// other. A token that is present but does not validate is a hard failure —
	// it must never fall through to the setup-key path, or an attacker with a
	// stale token and a valid setup key would be recorded as whichever identity
	// the token claimed.
	//
	// Single-use. The server registers each token so a captured one cannot
	// enrol a second node.
	JwtToken string `protobuf:"bytes,6,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
}

func (x *KarstLoginRequest) Reset() {
	*x = KarstLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstLoginRequest) ProtoMessage() {}

func (x *KarstLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstLoginRequest.ProtoReflect.Descriptor instead.
func (*KarstLoginRequest) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{0}
}

func (x *KarstLoginRequest) GetSetupKey() string {
	if x != nil {
		return x.SetupKey
	}
	return ""
}

func (x *KarstLoginRequest) GetMeta() *PeerSystemMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *KarstLoginRequest) GetDnsLabels() []string {
	if x != nil {
		return x.DnsLabels
	}
	return nil
}

func (x *KarstLoginRequest) GetKemPublicKey() []byte {
	if x != nil {
		return x.KemPublicKey
	}
	return nil
}

func (x *KarstLoginRequest) GetDhPublicKey() []byte {
	if x != nil {
		return x.DhPublicKey
	}
	return nil
}

func (x *KarstLoginRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

// KarstNetmapRequest asks for the caller's current view of the network.
type KarstNetmapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version the node already holds; zero means "I have nothing".
	//
	// The version is a CONTENT HASH, not a counter: identical netmaps always
	// yield the same version, so the server can answer "nothing changed" without
	// keeping per-node history — which is what preserves the O(1) server state
	// §2.6 chose. When it matches, the response sets `unchanged` and omits the
	// peer list.
	KnownVersion uint64 `protobuf:"varint,1,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	// What the node currently holds, one digest per peer.
	//
	// This is how delta push avoids per-node server history. The obvious design
	// — remember what each node was last sent — costs O(nodes x history) state
	// and gives up the O(1) property §2.6 chose deliberately. Instead the
	// *request* carries the state: the node says what it has, and the server
	// replies with only what differs.
	//
	// The saving is large because a digest is 8 bytes against roughly 2.4 KB for
	// a peer entry (a 1184-byte KEM key, a 32-byte DH key, two 32-byte PSKs,
	// addresses). At 200 peers that is a 1.6 KB request instead of a ~480 KB
	// response.
	//
	// Empty means "send everything", which is also what a first connection does.
	Holds []*KarstPeerDigest `protobuf:"bytes,2,rep,name=holds,proto3" json:"holds,omitempty"`
	// The relay this node has chosen to hold a connection to — ponor-v1.md §9.1.
	//
	// Reported on every netmap request rather than through a separate call: the
	// node is already talking to the server on a cadence, and a dedicated RPC
	// would be a second path to the same fact, free to disagree with this one.
	//
	// Empty means the node has no home relay — it is starting, or the netmap
	// listed none. That is distinct from "unchanged": a node that has released
	// its relay must be able to say so, or peers keep being told to reach it
	// somewhere nothing is listening.
	//
	// 32 bytes, the SHA-256 relay handle of KarstRelay.relay_id.
	HomeRelay []byte `protobuf:"bytes,3,opt,name=home_relay,json=homeRelay,proto3" json:"home_relay,omitempty"`
}

func (x *KarstNetmapRequest) Reset() {
	*x = KarstNetmapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstNetmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstNetmapRequest) ProtoMessage() {}

func (x *KarstNetmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstNetmapRequest.ProtoReflect.Descriptor instead.
func (*KarstNetmapRequest) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{1}
}

func (x *KarstNetmapRequest) GetKnownVersion() uint64 {
	if x != nil {
		return x.KnownVersion
	}
	return 0
}

func (x *KarstNetmapRequest) GetHolds() []*KarstPeerDigest {
	if x != nil {
		return x.Holds
	}
	return nil
}

func (x *KarstNetmapRequest) GetHomeRelay() []byte {
	if x != nil {
		return x.HomeRelay
	}
	return nil
}

// KarstPeerDigest is a node's summary of one peer entry it holds.
type KarstPeerDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Digest over the peer's routable content and the PSK epoch — never over the
	// PSK bytes themselves, for the same reason the netmap version excludes
	// them: a value the node computes and sends must not be a function of secret
	// material.
	//
	// Because a PSK is determined by (pair, epoch, master), covering the epoch
	// detects a rotation. It follows that **rotating the master key without
	// advancing the epoch would leave every digest unchanged and every node
	// holding a stale PSK**; the epoch must advance whenever the master does.
	Digest uint64 `protobuf:"varint,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *KarstPeerDigest) Reset() {
	*x = KarstPeerDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstPeerDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstPeerDigest) ProtoMessage() {}

func (x *KarstPeerDigest) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstPeerDigest.ProtoReflect.Descriptor instead.
func (*KarstPeerDigest) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{2}
}

func (x *KarstPeerDigest) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *KarstPeerDigest) GetDigest() uint64 {
	if x != nil {
		return x.Digest
	}
	return 0
}

// KarstNetmapPeer is one peer as the requesting node needs to see it.
type KarstNetmapPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId     []byte   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AllowedIps []string `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	DnsName    string   `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	Endpoint   string   `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The relay this peer holds a connection to — ponor-v1.md §9.1.
	//
	// How a node reaches a peer it has no direct path to and that is not on its
	// own relay's mesh: §9.1's second rule, an on-demand connection to the peer's
	// published home relay. Without it a cross-region pair has no rendezvous at
	// all, because §8 confines a mesh to one region on purpose.
	//
	// Empty means the peer has not reported one. A node MUST treat that as "no
	// second option" rather than guessing, since a guess would send a handshake
	// to a relay the peer is not connected to and wait out the timeout.
	HomeRelay []byte `protobuf:"bytes,10,opt,name=home_relay,json=homeRelay,proto3" json:"home_relay,omitempty"`
	// PHREATIC keys (phreatic-v1.md §4).
	KemPublicKey []byte `protobuf:"bytes,5,opt,name=kem_public_key,json=kemPublicKey,proto3" json:"kem_public_key,omitempty"` // S_pk, 1184 B
	DhPublicKey  []byte `protobuf:"bytes,6,opt,name=dh_public_key,json=dhPublicKey,proto3" json:"dh_public_key,omitempty"`    // D_pk, 32 B
	// The per-pair PSK for (recipient, this peer) at psk_epoch (PLAN.md §2.6).
	//
	// THIS FIELD IS THE REASON THE CONTROL CHANNEL HAS ITS OWN CRYPTOGRAPHIC
	// LAYER INSIDE TLS (ADR-0011). A netmap on the wire in plaintext hands every
	// PSK in the network to anything that terminates TLS. It must never be
	// logged; see package psk, where the type refuses to render.
	//
	// Empty means no PSK is available for this pair, and the node falls back to
	// an all-zero PSK (§2.6). Such sessions are lattice-only and must be flagged
	// in the crypto posture view.
	Psk []byte `protobuf:"bytes,7,opt,name=psk,proto3" json:"psk,omitempty"`
	// The same pair's PSK at psk_epoch - 1.
	//
	// phreatic-v1.md §7.3: "Responders MUST accept epoch n and n-1 and MUST
	// reject any other." Shipping only the current epoch would mean that during
	// a rotation, a node that has refetched cannot answer a peer that has not —
	// and §7.3's fallback would turn that into a silently lattice-only session
	// rather than a failure. Carrying both is what makes a rotation
	// uninterrupted *and* undegraded.
	//
	// Empty when psk_epoch is 0, which has no predecessor.
	PskPrevious []byte `protobuf:"bytes,8,opt,name=psk_previous,json=pskPrevious,proto3" json:"psk_previous,omitempty"`
	// The per-pair AVEN path-discovery key for (recipient, this peer) at
	// psk_epoch. It is domain-separated from psk and authenticated inside the
	// same protected control-plane envelope. Empty means discovery is disabled
	// for this peer; a node must keep using its relay path in that case.
	DiscoKey []byte `protobuf:"bytes,9,opt,name=disco_key,json=discoKey,proto3" json:"disco_key,omitempty"`
}

func (x *KarstNetmapPeer) Reset() {
	*x = KarstNetmapPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstNetmapPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstNetmapPeer) ProtoMessage() {}

func (x *KarstNetmapPeer) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstNetmapPeer.ProtoReflect.Descriptor instead.
func (*KarstNetmapPeer) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{3}
}

func (x *KarstNetmapPeer) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *KarstNetmapPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *KarstNetmapPeer) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *KarstNetmapPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *KarstNetmapPeer) GetHomeRelay() []byte {
	if x != nil {
		return x.HomeRelay
	}
	return nil
}

func (x *KarstNetmapPeer) GetKemPublicKey() []byte {
	if x != nil {
		return x.KemPublicKey
	}
	return nil
}

func (x *KarstNetmapPeer) GetDhPublicKey() []byte {
	if x != nil {
		return x.DhPublicKey
	}
	return nil
}

func (x *KarstNetmapPeer) GetPsk() []byte {
	if x != nil {
		return x.Psk
	}
	return nil
}

func (x *KarstNetmapPeer) GetPskPrevious() []byte {
	if x != nil {
		return x.PskPrevious
	}
	return nil
}

func (x *KarstNetmapPeer) GetDiscoKey() []byte {
	if x != nil {
		return x.DiscoKey
	}
	return nil
}

// KarstRelay is an authenticated Ponor relay registry entry. The node pins the
// ML-DSA key and checks the derived relay id during the Ponor handshake; TLS
// alone is deliberately not relay authentication (ponor-v1.md §4.2).
type KarstRelay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RelayId     []byte `protobuf:"bytes,2,opt,name=relay_id,json=relayId,proto3" json:"relay_id,omitempty"`             // SHA-256 relay handle, 32 B
	IdentityKey []byte `protobuf:"bytes,3,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"` // ML-DSA-65 public key, 1952 B
	Region      string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// DNS name used solely for TLS SNI and certificate validation. It is
	// separate from `address`: self-hosters often reach a relay through an IP or
	// load-balancer address while the certificate names the shared control host.
	// Ponor still authenticates the relay by `identity_key`, never this name.
	TlsServerName string `protobuf:"bytes,5,opt,name=tls_server_name,json=tlsServerName,proto3" json:"tls_server_name,omitempty"`
}

func (x *KarstRelay) Reset() {
	*x = KarstRelay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstRelay) ProtoMessage() {}

func (x *KarstRelay) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstRelay.ProtoReflect.Descriptor instead.
func (*KarstRelay) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{4}
}

func (x *KarstRelay) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KarstRelay) GetRelayId() []byte {
	if x != nil {
		return x.RelayId
	}
	return nil
}

func (x *KarstRelay) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *KarstRelay) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *KarstRelay) GetTlsServerName() string {
	if x != nil {
		return x.TlsServerName
	}
	return ""
}

type KarstNetmapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Selects which PSK generation these keys belong to; carried in PHREATIC
	// msg1 so the two ends agree on a generation (phreatic-v1.md §13.2).
	PskEpoch  uint32             `protobuf:"varint,2,opt,name=psk_epoch,json=pskEpoch,proto3" json:"psk_epoch,omitempty"`
	NodeId    []byte             `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses []string           `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	DnsName   string             `protobuf:"bytes,5,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
	Peers     []*KarstNetmapPeer `protobuf:"bytes,6,rep,name=peers,proto3" json:"peers,omitempty"`
	// The ACL-derived packet filter for this node (PLAN.md §4.3), compiled by
	// the server and enforced by the Rust datapath on BOTH ingress and egress.
	//
	// Compiled per node rather than shipped whole: a node learns nothing about
	// rules that do not involve it, so the netmap does not leak the shape of the
	// rest of the network.
	//
	// An empty list means DEFAULT DENY, not "unfiltered". A node that reads it
	// the other way inverts the policy — which is why `unchanged` exists as a
	// separate flag rather than being inferred from emptiness.
	PacketFilter []*KarstFilterRule `protobuf:"bytes,9,rep,name=packet_filter,json=packetFilter,proto3" json:"packet_filter,omitempty"`
	// Authenticated relay choices for this node. Replaced wholesale on every
	// non-unchanged response, just like packet_filter.
	Relays []*KarstRelay `protobuf:"bytes,13,rep,name=relays,proto3" json:"relays,omitempty"`
	// The same policy compiled for the traffic this node *originates* (§4.3).
	//
	// Not derivable from packet_filter: Karst's ACLs are unidirectional grants,
	// so a node's inbound rules say nothing about what it may send. Both are
	// needed for "enforced on both ends".
	//
	// The receiver's check is the one carrying the security property — a
	// compromised sender ignores its own filter. This one makes a denied flow
	// fail locally and immediately instead of being dropped after a round trip,
	// and keeps forbidden traffic away from a peer's crypto entirely.
	//
	// An empty list is DEFAULT DENY here too.
	EgressFilter []*KarstEgressRule `protobuf:"bytes,12,rep,name=egress_filter,json=egressFilter,proto3" json:"egress_filter,omitempty"`
	// True when `peers` contains only entries that changed, and `removed_peers`
	// names those to drop. False means `peers` is the complete set and anything
	// absent from it should be discarded.
	//
	// A node MUST NOT infer this from whether `removed_peers` is empty: a delta
	// with nothing removed and a full netmap that happens to list every peer are
	// otherwise indistinguishable, and reading one as the other either strands
	// removed peers or drops live ones.
	Delta bool `protobuf:"varint,10,opt,name=delta,proto3" json:"delta,omitempty"`
	// Peers to forget. Only meaningful when `delta` is true.
	RemovedPeers [][]byte `protobuf:"bytes,11,rep,name=removed_peers,json=removedPeers,proto3" json:"removed_peers,omitempty"`
	// True when the node's known_version already matched: `peers` is empty and
	// the node should keep what it has.
	//
	// Distinct from "an empty peer list", which is a real state — a node alone
	// in its network — and which a node must act on by dropping every peer it
	// holds. Conflating them would leave a removed peer configured forever.
	Unchanged bool `protobuf:"varint,7,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
}

func (x *KarstNetmapResponse) Reset() {
	*x = KarstNetmapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstNetmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstNetmapResponse) ProtoMessage() {}

func (x *KarstNetmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstNetmapResponse.ProtoReflect.Descriptor instead.
func (*KarstNetmapResponse) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{5}
}

func (x *KarstNetmapResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KarstNetmapResponse) GetPskEpoch() uint32 {
	if x != nil {
		return x.PskEpoch
	}
	return 0
}

func (x *KarstNetmapResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *KarstNetmapResponse) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *KarstNetmapResponse) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *KarstNetmapResponse) GetPeers() []*KarstNetmapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *KarstNetmapResponse) GetPacketFilter() []*KarstFilterRule {
	if x != nil {
		return x.PacketFilter
	}
	return nil
}

func (x *KarstNetmapResponse) GetRelays() []*KarstRelay {
	if x != nil {
		return x.Relays
	}
	return nil
}

func (x *KarstNetmapResponse) GetEgressFilter() []*KarstEgressRule {
	if x != nil {
		return x.EgressFilter
	}
	return nil
}

func (x *KarstNetmapResponse) GetDelta() bool {
	if x != nil {
		return x.Delta
	}
	return false
}

func (x *KarstNetmapResponse) GetRemovedPeers() [][]byte {
	if x != nil {
		return x.RemovedPeers
	}
	return nil
}

func (x *KarstNetmapResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

// KarstPortRange is inclusive at both ends. A single port is a range of one.
type KarstPortRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First uint32 `protobuf:"varint,1,opt,name=first,proto3" json:"first,omitempty"`
	Last  uint32 `protobuf:"varint,2,opt,name=last,proto3" json:"last,omitempty"`
}

func (x *KarstPortRange) Reset() {
	*x = KarstPortRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstPortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstPortRange) ProtoMessage() {}

func (x *KarstPortRange) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstPortRange.ProtoReflect.Descriptor instead.
func (*KarstPortRange) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{6}
}

func (x *KarstPortRange) GetFirst() uint32 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *KarstPortRange) GetLast() uint32 {
	if x != nil {
		return x.Last
	}
	return 0
}

// KarstFilterRule permits traffic from any of `srcs` to this node on `ports`.
type KarstFilterRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node handles, or "*" for any source.
	Srcs  []string          `protobuf:"bytes,1,rep,name=srcs,proto3" json:"srcs,omitempty"`
	Ports []*KarstPortRange `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *KarstFilterRule) Reset() {
	*x = KarstFilterRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstFilterRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstFilterRule) ProtoMessage() {}

func (x *KarstFilterRule) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstFilterRule.ProtoReflect.Descriptor instead.
func (*KarstFilterRule) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{7}
}

func (x *KarstFilterRule) GetSrcs() []string {
	if x != nil {
		return x.Srcs
	}
	return nil
}

func (x *KarstFilterRule) GetPorts() []*KarstPortRange {
	if x != nil {
		return x.Ports
	}
	return nil
}

// KarstEgressRule permits traffic from this node to any of `dsts` on `ports`.
//
// The mirror of KarstFilterRule. A separate message rather than the same one
// with a renamed field, because a rule whose direction is implied by which
// list it appears in is one substitution away from inverting a policy.
type KarstEgressRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Node handles, or "*" for any destination.
	Dsts  []string          `protobuf:"bytes,1,rep,name=dsts,proto3" json:"dsts,omitempty"`
	Ports []*KarstPortRange `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *KarstEgressRule) Reset() {
	*x = KarstEgressRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstEgressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstEgressRule) ProtoMessage() {}

func (x *KarstEgressRule) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstEgressRule.ProtoReflect.Descriptor instead.
func (*KarstEgressRule) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{8}
}

func (x *KarstEgressRule) GetDsts() []string {
	if x != nil {
		return x.Dsts
	}
	return nil
}

func (x *KarstEgressRule) GetPorts() []*KarstPortRange {
	if x != nil {
		return x.Ports
	}
	return nil
}

type KarstLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The server-assigned handle. Derived from the node's ML-DSA identity, and
	// the value to put in KarstEnvelope.node_id on later connections.
	NodeId  []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerIp  string `protobuf:"bytes,2,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	DnsName string `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
}

func (x *KarstLoginResponse) Reset() {
	*x = KarstLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstLoginResponse) ProtoMessage() {}

func (x *KarstLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstLoginResponse.ProtoReflect.Descriptor instead.
func (*KarstLoginResponse) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{9}
}

func (x *KarstLoginResponse) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *KarstLoginResponse) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *KarstLoginResponse) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

// KarstServerMessage is ChannelHello once, then envelopes.
type KarstServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*KarstServerMessage_Hello
	//	*KarstServerMessage_Envelope
	Msg isKarstServerMessage_Msg `protobuf_oneof:"msg"`
}

func (x *KarstServerMessage) Reset() {
	*x = KarstServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstServerMessage) ProtoMessage() {}

func (x *KarstServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstServerMessage.ProtoReflect.Descriptor instead.
func (*KarstServerMessage) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{10}
}

func (m *KarstServerMessage) GetMsg() isKarstServerMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *KarstServerMessage) GetHello() *ChannelHello {
	if x, ok := x.GetMsg().(*KarstServerMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *KarstServerMessage) GetEnvelope() *KarstEnvelope {
	if x, ok := x.GetMsg().(*KarstServerMessage_Envelope); ok {
		return x.Envelope
	}
	return nil
}

type isKarstServerMessage_Msg interface {
	isKarstServerMessage_Msg()
}

type KarstServerMessage_Hello struct {
	Hello *ChannelHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type KarstServerMessage_Envelope struct {
	Envelope *KarstEnvelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

func (*KarstServerMessage_Hello) isKarstServerMessage_Msg() {}

func (*KarstServerMessage_Envelope) isKarstServerMessage_Msg() {}

// KarstClientMessage is ChannelInit once, then envelopes.
type KarstClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*KarstClientMessage_Init
	//	*KarstClientMessage_Envelope
	Msg isKarstClientMessage_Msg `protobuf_oneof:"msg"`
}

func (x *KarstClientMessage) Reset() {
	*x = KarstClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstClientMessage) ProtoMessage() {}

func (x *KarstClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstClientMessage.ProtoReflect.Descriptor instead.
func (*KarstClientMessage) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{11}
}

func (m *KarstClientMessage) GetMsg() isKarstClientMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *KarstClientMessage) GetInit() *ChannelInit {
	if x, ok := x.GetMsg().(*KarstClientMessage_Init); ok {
		return x.Init
	}
	return nil
}

func (x *KarstClientMessage) GetEnvelope() *KarstEnvelope {
	if x, ok := x.GetMsg().(*KarstClientMessage_Envelope); ok {
		return x.Envelope
	}
	return nil
}

type isKarstClientMessage_Msg interface {
	isKarstClientMessage_Msg()
}

type KarstClientMessage_Init struct {
	Init *ChannelInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type KarstClientMessage_Envelope struct {
	Envelope *KarstEnvelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

func (*KarstClientMessage_Init) isKarstClientMessage_Msg() {}

func (*KarstClientMessage_Envelope) isKarstClientMessage_Msg() {}

// KarstEnvelope wraps every control-plane message once a channel is up.
//
// node_id is an authentication handle and a database index. It is *not* key
// material and no key operation is defined on it. That separation is the whole
// point of ADR-0011; do not add a field here that is both.
type KarstEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server-assigned, opaque. Empty only on the very first ChannelInit of a
	// registration, before an ID exists.
	NodeId []byte `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ChaCha20-Poly1305 ciphertext of the inner message under the channel key.
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Per-channel monotonic counter, and the AEAD nonce input. Never reused
	// under one channel key; a receiver rejects any seq it has already accepted.
	Seq uint64 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	// Envelope format version. 1 = the construction in ADR-0011.
	Version uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *KarstEnvelope) Reset() {
	*x = KarstEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KarstEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KarstEnvelope) ProtoMessage() {}

func (x *KarstEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KarstEnvelope.ProtoReflect.Descriptor instead.
func (*KarstEnvelope) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{12}
}

func (x *KarstEnvelope) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *KarstEnvelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *KarstEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *KarstEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ChannelHello opens a channel. Server speaks first: it must contribute
// freshness before the node signs anything, or the node's signature could be
// replayed onto another connection.
type ChannelHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifies which pinned static server key the node should encapsulate to,
	// so the server can rotate without breaking nodes mid-rotation.
	ServerKemPkId []byte `protobuf:"bytes,1,opt,name=server_kem_pk_id,json=serverKemPkId,proto3" json:"server_kem_pk_id,omitempty"`
	// Per-connection ephemeral ML-KEM-768 public key (1184 B).
	//
	// MUST be verified against `signature` before use. An earlier revision left
	// it unsigned on the reasoning that substituting it makes the channel fail
	// closed. That is true of authentication and false of forward secrecy:
	// ProVerif found a trace where the attacker sends the server's own *static*
	// public key as the ephemeral, the node encapsulates both ciphertexts to one
	// long-term key, and every recorded session decrypts when that key later
	// leaks. The node transmits before the channel dies, so "fails closed" does
	// not save it. See spec/models/karst-control.pv.
	EphKemPk []byte `protobuf:"bytes,2,opt,name=eph_kem_pk,json=ephKemPk,proto3" json:"eph_kem_pk,omitempty"`
	// 32 bytes of server randomness. The stream affords a round trip, so
	// freshness comes from the server rather than from a timestamp with a
	// clock-skew window as in PHREATIC msg1 (spec §5).
	ServerRandom []byte `protobuf:"bytes,3,opt,name=server_random,json=serverRandom,proto3" json:"server_random,omitempty"`
	// ML-DSA-65 signature (3309 B) by the server's identity key over
	//
	//	H("karst-control-hello-v1" ‖ server_random ‖ eph_kem_pk)
	//
	// This is what makes the ephemeral key genuinely ephemeral, and so what
	// makes forward secrecy real. The node pins the server's verification key at
	// enrolment alongside its static KEM key, and MUST abort if this does not
	// verify — before sending anything, because ChannelInit is followed
	// immediately by a request that may carry an auth key.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Version   uint32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ChannelHello) Reset() {
	*x = ChannelHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelHello) ProtoMessage() {}

func (x *ChannelHello) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelHello.ProtoReflect.Descriptor instead.
func (*ChannelHello) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{13}
}

func (x *ChannelHello) GetServerKemPkId() []byte {
	if x != nil {
		return x.ServerKemPkId
	}
	return nil
}

func (x *ChannelHello) GetEphKemPk() []byte {
	if x != nil {
		return x.EphKemPk
	}
	return nil
}

func (x *ChannelHello) GetServerRandom() []byte {
	if x != nil {
		return x.ServerRandom
	}
	return nil
}

func (x *ChannelHello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ChannelHello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ChannelInit answers it and establishes the channel key.
//
//	(ss_s, ct_static) = ML-KEM-768.Encaps(server_static_kem_pk)
//	(ss_e, ct_eph)    = ML-KEM-768.Encaps(eph_kem_pk)
//	k = HKDF-SHA-512(ss_s || ss_e,
//	      "karst-control-v1" || server_random || ct_static || ct_eph)
//
// Both encapsulations are load-bearing and neither is redundant: ct_static
// authenticates the server implicitly (only the real server can decapsulate
// it), ct_eph provides forward secrecy against later compromise of the
// server's static key. See ADR-0011 for why that matters here specifically —
// the netmap carries per-pair PSKs.
type ChannelInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ML-KEM-768 ciphertext to the server's pinned static key (1088 B).
	CtStatic []byte `protobuf:"bytes,1,opt,name=ct_static,json=ctStatic,proto3" json:"ct_static,omitempty"`
	// ML-KEM-768 ciphertext to the ephemeral key from ChannelHello (1088 B).
	CtEph []byte `protobuf:"bytes,2,opt,name=ct_eph,json=ctEph,proto3" json:"ct_eph,omitempty"`
	// ML-DSA-65 public key (1952 B). Present only when registering: a node that
	// already exists is looked up by node_id and its stored key is used. A
	// presented key is bound to the new node record on success.
	IdentityPk []byte `protobuf:"bytes,3,opt,name=identity_pk,json=identityPk,proto3" json:"identity_pk,omitempty"`
	// Empty during first registration.
	NodeId []byte `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// ML-DSA-65 signature (3309 B) over
	//
	//	"karst-control-init-v1" || server_random || ct_static || ct_eph || node_id
	//
	// Only the init is signed. Because the signature covers both ciphertexts and
	// k derives from them, possession of k on later messages is already
	// attributable to whoever signed this. Signing every message would cost
	// 3309 B to prove what the AEAD proves for free.
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Version   uint32 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ChannelInit) Reset() {
	*x = ChannelInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_karst_control_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInit) ProtoMessage() {}

func (x *ChannelInit) ProtoReflect() protoreflect.Message {
	mi := &file_karst_control_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInit.ProtoReflect.Descriptor instead.
func (*ChannelInit) Descriptor() ([]byte, []int) {
	return file_karst_control_proto_rawDescGZIP(), []int{14}
}

func (x *ChannelInit) GetCtStatic() []byte {
	if x != nil {
		return x.CtStatic
	}
	return nil
}

func (x *ChannelInit) GetCtEph() []byte {
	if x != nil {
		return x.CtEph
	}
	return nil
}

func (x *ChannelInit) GetIdentityPk() []byte {
	if x != nil {
		return x.IdentityPk
	}
	return nil
}

func (x *ChannelInit) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *ChannelInit) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ChannelInit) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_karst_control_proto protoreflect.FileDescriptor

var file_karst_control_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x61, 0x72, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x1a, 0x10, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x01, 0x0a, 0x11, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x74,
	0x75, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x74, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x6e, 0x73, 0x5f, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x6e, 0x73, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x6b, 0x65, 0x6d, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6b,
	0x65, 0x6d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x64,
	0x68, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x64, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x1b, 0x0a, 0x09, 0x6a, 0x77, 0x74, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x8b, 0x01, 0x0a,
	0x12, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x05, 0x68, 0x6f, 0x6c, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x44, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x6c, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x6f, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x68, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x42, 0x0a, 0x0f, 0x4b, 0x61,
	0x72, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0xbd,
	0x02, 0x0a, 0x0f, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x6d, 0x61, 0x70, 0x50, 0x65,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x6e, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x6c, 0x61,
	0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x68, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x6b, 0x65, 0x6d, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6b, 0x65, 0x6d, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x64, 0x68, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x64, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x73, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x73, 0x6b, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x73, 0x6b, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x73, 0x6b, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x4b, 0x65, 0x79, 0x22, 0xa4,
	0x01, 0x0a, 0x0a, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x61, 0x79,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a,
	0x0f, 0x74, 0x6c, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xde, 0x03, 0x0a, 0x13, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4e,
	0x65, 0x74, 0x6d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x73, 0x6b, 0x5f, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x73, 0x6b, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x64,
	0x6e, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4e, 0x65, 0x74, 0x6d, 0x61, 0x70, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0d, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61,
	0x72, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x0c, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x72,
	0x65, 0x6c, 0x61, 0x79, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x52, 0x65,
	0x6c, 0x61, 0x79, 0x52, 0x06, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x73, 0x12, 0x40, 0x0a, 0x0d, 0x65,
	0x67, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x4b, 0x61, 0x72, 0x73, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x0c, 0x65, 0x67, 0x72, 0x65, 0x73, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x70,
	0x65, 0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x6e, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x75, 0x6e, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x22, 0x3a, 0x0a, 0x0e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x61,
	0x73, 0x74, 0x22, 0x57, 0x0a, 0x0f, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x72, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x73, 0x72, 0x63, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x57, 0x0a, 0x0f, 0x4b,
	0x61, 0x72, 0x73, 0x74, 0x45, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x73,
	0x74, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b,
	0x61, 0x72, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x22, 0x61, 0x0a, 0x12, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x70, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x6e, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x4b, 0x61, 0x72, 0x73,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30,
	0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x4b, 0x61, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x83, 0x01, 0x0a, 0x12, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x42,
	0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x68, 0x0a, 0x0d, 0x4b, 0x61, 0x72, 0x73, 0x74, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x27, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x6d, 0x5f,
	0x70, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4b, 0x65, 0x6d, 0x50, 0x6b, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x65, 0x70,
	0x68, 0x5f, 0x6b, 0x65, 0x6d, 0x5f, 0x70, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x65, 0x70, 0x68, 0x4b, 0x65, 0x6d, 0x50, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x74, 0x5f, 0x65, 0x70, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x63, 0x74, 0x45, 0x70, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x66, 0x0a, 0x13, 0x4b,
	0x61, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4f, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1e, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4b, 0x61, 0x72, 0x73, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_karst_control_proto_rawDescOnce sync.Once
	file_karst_control_proto_rawDescData = file_karst_control_proto_rawDesc
)

func file_karst_control_proto_rawDescGZIP() []byte {
	file_karst_control_proto_rawDescOnce.Do(func() {
		file_karst_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_karst_control_proto_rawDescData)
	})
	return file_karst_control_proto_rawDescData
}

var file_karst_control_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_karst_control_proto_goTypes = []interface{}{
	(*KarstLoginRequest)(nil),   // 0: management.KarstLoginRequest
	(*KarstNetmapRequest)(nil),  // 1: management.KarstNetmapRequest
	(*KarstPeerDigest)(nil),     // 2: management.KarstPeerDigest
	(*KarstNetmapPeer)(nil),     // 3: management.KarstNetmapPeer
	(*KarstRelay)(nil),          // 4: management.KarstRelay
	(*KarstNetmapResponse)(nil), // 5: management.KarstNetmapResponse
	(*KarstPortRange)(nil),      // 6: management.KarstPortRange
	(*KarstFilterRule)(nil),     // 7: management.KarstFilterRule
	(*KarstEgressRule)(nil),     // 8: management.KarstEgressRule
	(*KarstLoginResponse)(nil),  // 9: management.KarstLoginResponse
	(*KarstServerMessage)(nil),  // 10: management.KarstServerMessage
	(*KarstClientMessage)(nil),  // 11: management.KarstClientMessage
	(*KarstEnvelope)(nil),       // 12: management.KarstEnvelope
	(*ChannelHello)(nil),        // 13: management.ChannelHello
	(*ChannelInit)(nil),         // 14: management.ChannelInit
	(*PeerSystemMeta)(nil),      // 15: management.PeerSystemMeta
}
var file_karst_control_proto_depIdxs = []int32{
	15, // 0: management.KarstLoginRequest.meta:type_name -> management.PeerSystemMeta
	2,  // 1: management.KarstNetmapRequest.holds:type_name -> management.KarstPeerDigest
	3,  // 2: management.KarstNetmapResponse.peers:type_name -> management.KarstNetmapPeer
	7,  // 3: management.KarstNetmapResponse.packet_filter:type_name -> management.KarstFilterRule
	4,  // 4: management.KarstNetmapResponse.relays:type_name -> management.KarstRelay
	8,  // 5: management.KarstNetmapResponse.egress_filter:type_name -> management.KarstEgressRule
	6,  // 6: management.KarstFilterRule.ports:type_name -> management.KarstPortRange
	6,  // 7: management.KarstEgressRule.ports:type_name -> management.KarstPortRange
	13, // 8: management.KarstServerMessage.hello:type_name -> management.ChannelHello
	12, // 9: management.KarstServerMessage.envelope:type_name -> management.KarstEnvelope
	14, // 10: management.KarstClientMessage.init:type_name -> management.ChannelInit
	12, // 11: management.KarstClientMessage.envelope:type_name -> management.KarstEnvelope
	11, // 12: management.KarstControlService.Session:input_type -> management.KarstClientMessage
	10, // 13: management.KarstControlService.Session:output_type -> management.KarstServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_karst_control_proto_init() }
func file_karst_control_proto_init() {
	if File_karst_control_proto != nil {
		return
	}
	file_management_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_karst_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstNetmapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstPeerDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstNetmapPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstRelay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstNetmapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstPortRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstFilterRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstEgressRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KarstEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_karst_control_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChannelInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_karst_control_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*KarstServerMessage_Hello)(nil),
		(*KarstServerMessage_Envelope)(nil),
	}
	file_karst_control_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*KarstClientMessage_Init)(nil),
		(*KarstClientMessage_Envelope)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_karst_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_karst_control_proto_goTypes,
		DependencyIndexes: file_karst_control_proto_depIdxs,
		MessageInfos:      file_karst_control_proto_msgTypes,
	}.Build()
	File_karst_control_proto = out.File
	file_karst_control_proto_rawDesc = nil
	file_karst_control_proto_goTypes = nil
	file_karst_control_proto_depIdxs = nil
}
