// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KarstControlServiceClient is the client API for KarstControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KarstControlServiceClient interface {
	// Session carries the whole node<->server relationship on one stream.
	//
	// Bidirectional because the server must speak first: it contributes the
	// freshness the node signs over (ADR-0011). A unary handshake would either
	// lose that or need a round trip to fetch a challenge.
	//
	// Named Session rather than Connect because tonic generates a client method
	// per RPC, and a `connect` method would collide with the generated client's
	// own `connect` constructor. A protocol whose method names depend on the
	// generator is fragile; this one does not have to be.
	Session(ctx context.Context, opts ...grpc.CallOption) (KarstControlService_SessionClient, error)
}

type karstControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKarstControlServiceClient(cc grpc.ClientConnInterface) KarstControlServiceClient {
	return &karstControlServiceClient{cc}
}

func (c *karstControlServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (KarstControlService_SessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &KarstControlService_ServiceDesc.Streams[0], "/management.KarstControlService/Session", opts...)
	if err != nil {
		return nil, err
	}
	x := &karstControlServiceSessionClient{stream}
	return x, nil
}

type KarstControlService_SessionClient interface {
	Send(*KarstClientMessage) error
	Recv() (*KarstServerMessage, error)
	grpc.ClientStream
}

type karstControlServiceSessionClient struct {
	grpc.ClientStream
}

func (x *karstControlServiceSessionClient) Send(m *KarstClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *karstControlServiceSessionClient) Recv() (*KarstServerMessage, error) {
	m := new(KarstServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KarstControlServiceServer is the server API for KarstControlService service.
// All implementations must embed UnimplementedKarstControlServiceServer
// for forward compatibility
type KarstControlServiceServer interface {
	// Session carries the whole node<->server relationship on one stream.
	//
	// Bidirectional because the server must speak first: it contributes the
	// freshness the node signs over (ADR-0011). A unary handshake would either
	// lose that or need a round trip to fetch a challenge.
	//
	// Named Session rather than Connect because tonic generates a client method
	// per RPC, and a `connect` method would collide with the generated client's
	// own `connect` constructor. A protocol whose method names depend on the
	// generator is fragile; this one does not have to be.
	Session(KarstControlService_SessionServer) error
	mustEmbedUnimplementedKarstControlServiceServer()
}

// UnimplementedKarstControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKarstControlServiceServer struct {
}

func (UnimplementedKarstControlServiceServer) Session(KarstControlService_SessionServer) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedKarstControlServiceServer) mustEmbedUnimplementedKarstControlServiceServer() {}

// UnsafeKarstControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KarstControlServiceServer will
// result in compilation errors.
type UnsafeKarstControlServiceServer interface {
	mustEmbedUnimplementedKarstControlServiceServer()
}

func RegisterKarstControlServiceServer(s grpc.ServiceRegistrar, srv KarstControlServiceServer) {
	s.RegisterService(&KarstControlService_ServiceDesc, srv)
}

func _KarstControlService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KarstControlServiceServer).Session(&karstControlServiceSessionServer{stream})
}

type KarstControlService_SessionServer interface {
	Send(*KarstServerMessage) error
	Recv() (*KarstClientMessage, error)
	grpc.ServerStream
}

type karstControlServiceSessionServer struct {
	grpc.ServerStream
}

func (x *karstControlServiceSessionServer) Send(m *KarstServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *karstControlServiceSessionServer) Recv() (*KarstClientMessage, error) {
	m := new(KarstClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KarstControlService_ServiceDesc is the grpc.ServiceDesc for KarstControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KarstControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "management.KarstControlService",
	HandlerType: (*KarstControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _KarstControlService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "karst_control.proto",
}
