#!/usr/bin/env bash
# Generate the deliberately-broken ProVerif variants.
#
# Two kinds, for two different jobs:
#
#   * phreatic-{kem,dh}-broken   — a whole primitive family is given to the
#     attacker. ADR-0002 claims security if EITHER family holds; these test
#     that by breaking one at a time. Both are expected to PASS.
#
#   * ponor-norelayid            — one field is dropped from one signature.
#     Expected to FAIL, and it is kept precisely so that a run in which it
#     passes tells us ponor.pv has stopped testing anything.
set -euo pipefail
cd "$(dirname "$0")"

hdr() { printf '(* GENERATED by gen-variants.sh — do not edit. Source: phreatic.pv *)\n(* %s *)\n\n' "$1"; }

# ── A: ML-KEM totally broken ────────────────────────────────────────────────
# A public destructor recovering the shared secret from any ciphertext.
{
  hdr "Direction A: ML-KEM BROKEN. Confidentiality must survive via X25519 + PSK."
  sed 's|^reduc forall sk: skem, r: rnd;$|(* total ML-KEM break: anyone recovers the shared secret *)\nreduc forall p: pkem, r: rnd;\n    break_kem(encap_ct(p, r)) = encap_ss(p, r).\n\nreduc forall sk: skem, r: rnd;|' phreatic.pv
} > phreatic-kem-broken.pv

# ── B: X25519 totally broken (the quantum adversary) ────────────────────────
# A public discrete-log destructor.
{
  hdr "Direction B: X25519 BROKEN. Confidentiality must survive via ML-KEM + PSK."
  sed 's|^equation forall x: exponent, y: exponent;$|(* total X25519 break: discrete log is computable *)\nreduc forall x: exponent;\n    dlog(exp(g, x)) = x.\n\nequation forall x: exponent, y: exponent;|' phreatic.pv
} > phreatic-dh-broken.pv

# ── C: Ponor with relay_id unbound in the client's signature ────────────────
# Not a broken primitive — a missing field. The client still CHECKS the
# relay's identity locally (spec §4.2); it just no longer signs over it. That
# distinction is the whole point: checking who you are talking to is not the
# same as binding it into what you sign.
#
# Expected to FAIL queries 1 and 3 (the relay authenticating a peer) and to
# PASS 2 and 4 (a peer authenticating the relay), because only the client's
# signing input is touched.
{
  printf '(* GENERATED by gen-variants.sh — do not edit. Source: ponor.pv *)\n'
  printf '(* relay_id UNBOUND in the client signature. EXPECTED: 2 true, 2 false. *)\n\n'
  sed 's|^    H(cat(CLBL, cat(rid, cat(rrand, cat(crand, cat(pid, role)))))).$|    (* relay_id dropped: the client signs a transcript that is valid at any\n       relay able to choose its relay_random — which a rogue relay can, by\n       copying the honest relay'"'"'s. *)\n    H(cat(CLBL, cat(rrand, cat(crand, cat(pid, role))))).|' ponor.pv
} > ponor-norelayid.pv

echo "Generated phreatic-kem-broken.pv, phreatic-dh-broken.pv and ponor-norelayid.pv"
