#!/usr/bin/env bash
# Generate the broken-primitive ProVerif variants from phreatic.pv.
# ADR-0002 claims security if EITHER cryptographic family holds; these two
# files test that by giving the attacker a total break of one family at a time.
set -euo pipefail
cd "$(dirname "$0")"

hdr() { printf '(* GENERATED by gen-variants.sh — do not edit. Source: phreatic.pv *)\n(* %s *)\n\n' "$1"; }

# ── A: ML-KEM totally broken ────────────────────────────────────────────────
# A public destructor recovering the shared secret from any ciphertext.
{
  hdr "Direction A: ML-KEM BROKEN. Confidentiality must survive via X25519 + PSK."
  sed 's|^reduc forall sk: skem, r: rnd;$|(* total ML-KEM break: anyone recovers the shared secret *)\nreduc forall p: pkem, r: rnd;\n    break_kem(encap_ct(p, r)) = encap_ss(p, r).\n\nreduc forall sk: skem, r: rnd;|' phreatic.pv
} > phreatic-kem-broken.pv

# ── B: X25519 totally broken (the quantum adversary) ────────────────────────
# A public discrete-log destructor.
{
  hdr "Direction B: X25519 BROKEN. Confidentiality must survive via ML-KEM + PSK."
  sed 's|^equation forall x: exponent, y: exponent;$|(* total X25519 break: discrete log is computable *)\nreduc forall x: exponent;\n    dlog(exp(g, x)) = x.\n\nequation forall x: exponent, y: exponent;|' phreatic.pv
} > phreatic-dh-broken.pv

echo "Generated phreatic-kem-broken.pv and phreatic-dh-broken.pv"
