#!/usr/bin/env bash
# Generate the deliberately-broken ProVerif variants.
#
# Two kinds, for two different jobs:
#
#   * phreatic-kem-broken — all KEM shared secrets become public.
#     The PSK is the remaining confidentiality contribution (ADR-0018).
#
#   * ponor-norelayid            — one field is dropped from one signature.
#     Expected to FAIL, and it is kept precisely so that a run in which it
#     passes tells us ponor.pv has stopped testing anything.
set -euo pipefail
cd "$(dirname "$0")"

hdr() { printf '(* GENERATED by gen-variants.sh — do not edit. Source: phreatic.pv *)\n(* %s *)\n\n' "$1"; }

# ── A: ML-KEM totally broken ────────────────────────────────────────────────
# A public destructor recovering the shared secret from any ciphertext.
{
  hdr "ML-KEM BROKEN. The private per-pair PSK is the remaining confidentiality contribution."
  sed 's|^reduc forall sk: skem, r: rnd;$|(* total ML-KEM break: anyone recovers the shared secret *)\nreduc forall p: pkem, r: rnd;\n    break_kem(encap_ct(p, r)) = encap_ss(p, r).\n\nreduc forall sk: skem, r: rnd;|' phreatic.pv
} > phreatic-kem-broken.pv

# ── C: Ponor with relay_id unbound in the client's signature ────────────────
# Not a broken primitive — a missing field. The client still CHECKS the
# relay's identity locally (spec §4.2); it just no longer signs over it. That
# distinction is the whole point: checking who you are talking to is not the
# same as binding it into what you sign.
#
# Expected to FAIL queries 1 and 3 (the relay authenticating a peer) and to
# PASS 2 and 4 (a peer authenticating the relay), because only the client's
# signing input is touched.
{
  printf '(* GENERATED by gen-variants.sh — do not edit. Source: ponor.pv *)\n'
  printf '(* relay_id UNBOUND in the client signature. EXPECTED: 2 true, 2 false. *)\n\n'
  sed 's|^    H(cat(CLBL, cat(rid, cat(rrand, cat(crand, cat(pid, role)))))).$|    (* relay_id dropped: the client signs a transcript that is valid at any\n       relay able to choose its relay_random — which a rogue relay can, by\n       copying the honest relay'"'"'s. *)\n    H(cat(CLBL, cat(rrand, cat(crand, cat(pid, role))))).|' ponor.pv
} > ponor-norelayid.pv

# ── D: AVEN with the MAC covering only the header ───────────────────────────
# Not hypothetical. phreatic-v1.md §13.8 made exactly this trade on the data
# path — deliberately, for a measured 5x saving — and this variant is why it
# must not be carried over to AVEN. With tx_id outside the MAC an attacker
# rewrites it on a captured Pong and confirms a path the peer never answered
# from.
#
# Expected to FAIL query 1 and PASS 2 and 3.
{
  printf '(* GENERATED by gen-variants.sh — do not edit. Source: aven.pv *)\n'
  printf '(* MAC covers the HEADER ONLY. EXPECTED: 2 true, 1 false. *)\n\n'
  sed -e 's|^    if m = mac(k, cat(PONG, cat(t, cat(tx2, obs)))) then$|    (* header only: tx_id and the observed address are unauthenticated *)\n    if m = mac(k, PONG) then|' \
      -e 's|out(c, (PONG, TAG_B, tx, obs, mac(k, cat(PONG, cat(TAG_B, cat(tx, obs))))))|out(c, (PONG, TAG_B, tx, obs, mac(k, PONG)))|' \
      aven.pv
} > aven-headeronly.pv

echo "Generated phreatic-kem-broken.pv, ponor-norelayid.pv and aven-headeronly.pv"
