// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright the Karst contributors.

//! **The Go server writes this file and this relay reads it.**
//!
//! `spec/vectors/relay-roster-v1.toml` is generated by
//! `server/management/internals/karst/roster`'s `TestRosterVector`, which is
//! the coordination server's roster renderer for a co-located relay
//! (PLAN.md §5). The two are separate implementations of one format, and until
//! this file existed nothing checked that they agreed.
//!
//! The failure this prevents is quiet and total. Admission is structural —
//! `ClientAuth` carries no public key, so a relay verifies against a roster
//! entry or not at all (`ponor-v1.md` §5.3) — so a renamed field on either side
//! does not produce a parse error at the relay. It produces a roster with
//! **zero clients**, a relay that starts cleanly, and a fleet that cannot
//! connect for reasons no log line explains. This is the same argument
//! `spec/vectors/karst-control-v1.json` makes for the wire formats.

#![allow(clippy::panic, clippy::expect_used, clippy::unwrap_used)]

use std::path::PathBuf;

use karst_relay::roster::FileRoster;

fn vector() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../spec/vectors/relay-roster-v1.toml")
}

#[test]
fn the_relay_parses_the_roster_the_control_server_renders() {
    let roster = FileRoster::load(&vector()).unwrap_or_else(|e| {
        panic!(
            "the relay cannot parse the roster karst-control writes: {e}\n\
             Regenerate with `UPDATE_VECTORS=1 go test ./management/internals/karst/roster/` \
             and check both sides."
        )
    });

    // Two clients, and — the part that matters — **not zero**. A field rename
    // on either side yields an empty roster rather than an error, so a test
    // that only checked "it parses" would pass against the failure it exists
    // to catch.
    assert_eq!(
        roster.client_count(),
        2,
        "the roster parsed but admitted nobody, which is what a renamed field \
         looks like from this side"
    );
    assert_eq!(roster.mesh_count(), 0, "a client is not a mesh peer");
}

#[test]
fn the_aquifer_survives_the_round_trip() {
    // §5.4 scopes forwarding per aquifer, so an aquifer that arrived as an
    // empty string would put every node in one namespace — a multi-tenant
    // relay becoming a message bus between any two keys it has heard of.
    let roster = FileRoster::load(&vector()).expect("parse");
    let aquifers = roster.aquifers();
    assert_eq!(
        aquifers,
        vec!["vector-aquifer".to_owned()],
        "the aquifer the Go renderer wrote is not the one this side read"
    );
}
