// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright the Karst contributors.

//! **The Go server writes this file and this relay's `signing_input` must
//! reproduce it, byte for byte.**
//!
//! `spec/vectors/relay-telemetry-v1.json` is generated by
//! `server/management/internals/karst/relaytelemetry`'s `TestVectors` — the
//! coordination server's own construction of ADR-0021's 80-byte telemetry
//! signing input. The two are separate implementations of one layout, and
//! until this file existed nothing checked that they agreed.
//!
//! The failure this prevents is quiet rather than loud: a field reordered or
//! a width changed from 8 bytes to 4 on either side still produces *a*
//! signature that verifies against *that* side's own construction — every
//! unit test in `telemetry.rs` and `relaytelemetry_test.go` would keep
//! passing. It only breaks once the relay's report meets the other
//! implementation's verifier, and then it fails as "telemetry report
//! rejected" — indistinguishable, by the server's own uniform-rejection
//! design, from a wrong signature or an unregistered relay.

#![allow(clippy::panic, clippy::expect_used, clippy::unwrap_used)]

use std::path::PathBuf;

use karst_relay::telemetry::signing_input;
use serde::Deserialize;

#[derive(Deserialize)]
struct VectorFile {
    signing_input: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    relay_id: String,
    timestamp: u64,
    local_clients: u64,
    mesh_peers: u64,
    remote_clients: u64,
    bytes_total: u64,
    uptime_secs: u64,
    expected: String,
}

fn vector() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../spec/vectors/relay-telemetry-v1.json")
}

#[test]
fn the_relay_builds_the_same_signing_input_the_control_server_does() {
    let text = std::fs::read_to_string(vector()).unwrap_or_else(|e| {
        panic!("cannot read {}: {e}", vector().display());
    });
    let file: VectorFile = serde_json::from_str(&text).expect("vector file is valid JSON");
    assert!(
        !file.signing_input.is_empty(),
        "the vector file has no cases"
    );

    for (i, case) in file.signing_input.iter().enumerate() {
        let relay_id: [u8; 32] = hex::decode(&case.relay_id)
            .unwrap_or_else(|e| panic!("case {i}: relay_id is not hex: {e}"))
            .try_into()
            .unwrap_or_else(|v: Vec<u8>| {
                panic!("case {i}: relay_id is {} bytes, want 32", v.len())
            });
        let expected = hex::decode(&case.expected)
            .unwrap_or_else(|e| panic!("case {i}: expected is not hex: {e}"));

        let got = signing_input(
            &relay_id,
            case.timestamp,
            case.local_clients,
            case.mesh_peers,
            case.remote_clients,
            case.bytes_total,
            case.uptime_secs,
        );

        assert_eq!(
            got, expected,
            "case {i}: this relay's signing_input disagrees with the Go server's \
             signingInput — regenerate with `UPDATE_VECTORS=1 go test \
             ./management/internals/karst/relaytelemetry/ -run Vectors` if this is an \
             intended layout change, and update signing_input to match"
        );
    }
}
