// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.

package channel

// Exports for cross-implementation vector generation.
//
// These are the pure functions where the Go server and the Rust node must
// agree byte-for-byte. They are exported rather than reimplemented in a test
// so that the vectors come from the same code the server runs — a vector
// generated by a reimplementation proves only that the reimplementation agrees
// with itself.

// DeriveKeysForTest exposes the key schedule.
func DeriveKeysForTest(ssStatic, ssEph, serverRandom, ctStatic, ctEph []byte) (c2s, s2c []byte, err error) {
	return deriveKeys(ssStatic, ssEph, serverRandom, ctStatic, ctEph)
}

// SealForTest exposes the record layer's framing under a caller-chosen key and
// sequence number, which a Channel deliberately does not allow.
func SealForTest(key, nodeID []byte, seq uint64, plaintext []byte) ([]byte, error) {
	ch, err := newChannel(key, key, true)
	if err != nil {
		return nil, err
	}
	return ch.sendAEAD.Seal(nil, nonceFor(seq), plaintext, associatedData(nodeID, seq)), nil
}
