#!/bin/sh
# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright the Karst contributors.
#
# Generates everything the co-located deployment needs and cannot invent for
# itself: a relay identity, a TLS certificate, the relay registry nodes are told
# about, and a starting roster.
#
# Idempotent. Every step skips if its output exists, so re-running after a
# partial failure finishes the job rather than replacing the keys that already
# work — regenerating a relay identity silently invalidates the registry every
# node has pinned.
#
# Run it once, then `docker compose up -d`.

set -eu

here=$(cd "$(dirname "$0")" && pwd)
state="$here/state"

relay_image=${KARST_RELAY_IMAGE:-ghcr.io/karst-net/karst-relay:dev}
aquifer=${KARST_AQUIFER:-default}
region=${KARST_REGION:-default}
server_name=${KARST_RELAY_SERVER_NAME:-relay.karst.local}
relay_port=${KARST_RELAY_PORT:-443}

# The address nodes will dial. **IP:port, not a name**: karstd parses this with
# Rust's SocketAddr, which does not resolve, and a name here produces a netmap
# every node rejects in full rather than one relay they skip. The name lives in
# tls_server_name, which is a separate field for exactly this reason.
if [ -z "${KARST_RELAY_IP:-}" ]; then
    cat >&2 <<EOF
KARST_RELAY_IP is not set.

It must be the address nodes dial to reach this relay, as an IP address — the
host's public IP for a real deployment, or 127.0.0.1 to try this on one machine.
It is not resolved, so a DNS name will not work here; put the name in
KARST_RELAY_SERVER_NAME instead, which is what the certificate is issued for.

    KARST_RELAY_IP=203.0.113.7 ./bootstrap.sh
EOF
    exit 1
fi
relay_address="$KARST_RELAY_IP:$relay_port"

need() {
    command -v "$1" >/dev/null 2>&1 || { echo "bootstrap: $1 is required but not installed" >&2; exit 1; }
}
need docker
need openssl

mkdir -p "$state/tls" "$state/netbird"

# ---------------------------------------------------------------------------
# 1. The relay's TLS certificate.
#
# Self-signed is not a compromise here. ponor-v1.md §4.2 declines to trust
# certificates for relay identity at all — a node authenticates a relay by the
# ML-DSA-65 key pinned in its netmap — so this certificate only has to get a TLS
# session established. Replace it with a CA-issued one if you like; it changes
# nothing about who the relay is proved to be.
# ---------------------------------------------------------------------------
if [ ! -f "$state/tls/relay.crt" ]; then
    echo "bootstrap: issuing a self-signed certificate for $server_name"
    openssl req -x509 -newkey rsa:4096 -sha256 -days 825 -nodes \
        -keyout "$state/tls/relay.key" -out "$state/tls/relay.crt" \
        -subj "/CN=$server_name" \
        -addext "subjectAltName=DNS:$server_name,IP:$KARST_RELAY_IP" >/dev/null 2>&1
    chmod 600 "$state/tls/relay.key"
else
    echo "bootstrap: keeping the existing certificate"
fi

# ---------------------------------------------------------------------------
# 2. The relay's configuration.
# ---------------------------------------------------------------------------
if [ ! -f "$state/relay.toml" ]; then
    cat > "$state/relay.toml" <<EOF
# Generated by bootstrap.sh. Safe to edit; it is not rewritten.
listen = "0.0.0.0:443"
identity_key = "/var/lib/karst/relay.key"
roster = "/var/lib/karst/roster.toml"
tls_cert = "/var/lib/karst/tls/relay.crt"
tls_key = "/var/lib/karst/tls/relay.key"
region = "$region"
EOF
fi

# A roster the relay can start on. Empty is a legitimate state — it admits
# nobody — and the coordination server replaces it within 25 seconds. Without
# some file here the relay would exit at startup rather than wait.
if [ ! -f "$state/roster.toml" ]; then
    printf '# Placeholder. karst-control overwrites this every 25s.\n' > "$state/roster.toml"
fi

# ---------------------------------------------------------------------------
# 3. The relay's identity, and the registry built from it.
#
# `pubkey` creates the seed on first run and prints the public half. The
# registry is derived from what the relay actually holds rather than typed
# twice: a node pins the key the registry names, so a mismatch is a relay
# nobody can authenticate.
# ---------------------------------------------------------------------------
if [ ! -f "$state/relays.json" ]; then
    echo "bootstrap: creating the relay identity"
    identity=$(docker run --rm -v "$state:/var/lib/karst" "$relay_image" \
        pubkey --config /var/lib/karst/relay.toml | awk '/^identity_pk/ { print $2 }')
    if [ -z "$identity" ]; then
        echo "bootstrap: karst-relay did not print an identity key" >&2
        exit 1
    fi
    cat > "$state/relays.json" <<EOF
{
  "relays": [
    {
      "address": "$relay_address",
      "tls_server_name": "$server_name",
      "identity_key": "$identity",
      "region": "$region"
    }
  ]
}
EOF
    echo "bootstrap: registry written for $relay_address"
else
    echo "bootstrap: keeping the existing relay identity and registry"
fi

# ---------------------------------------------------------------------------
# 4. The packet filter.
#
# An absent policy compiles to an empty filter, which is DEFAULT DENY: nothing
# would pass and the deployment would look broken. This one is the opposite and
# says so, because a starting point you can see is better than one you cannot.
# ---------------------------------------------------------------------------
if [ ! -f "$state/policy.json" ]; then
    # No explanatory key in the file itself: policy.Parse refuses unknown
    # fields, so a comment smuggled in as one would stop the server booting.
    cat > "$state/policy.json" <<'EOF'
{
  "acls": [
    { "action": "accept", "src": ["*"], "dst": ["*:*"] }
  ]
}
EOF
    echo "bootstrap: policy.json allows every node to reach every other node on"
    echo "           every port. Narrow it before you rely on it."
fi

# ---------------------------------------------------------------------------
# 5. The coordination server's own configuration.
# ---------------------------------------------------------------------------
if [ ! -f "$state/management.json" ]; then
    key=$(openssl rand -base64 32)
    cat > "$state/management.json" <<EOF
{
  "Stuns": [],
  "TURNConfig": { "Turns": [], "CredentialsTTL": "12h", "Secret": "$(openssl rand -hex 16)", "TimeBasedCredentials": false },
  "Signal": { "Proto": "http", "URI": "localhost:10000" },
  "Datadir": "/var/lib/netbird",
  "DataStoreEncryptionKey": "$key",
  "StoreConfig": { "Engine": "sqlite" },
  "HttpConfig": { "Address": "0.0.0.0:33071", "AuthIssuer": "", "AuthAudience": "", "AuthKeysLocation": "" }
}
EOF
    chmod 600 "$state/management.json"
fi

cat <<EOF

bootstrap: done. Next:

    docker compose up -d
    docker compose logs control | grep 'karst: server'

The two pins in that output — the KEM key and the signing key — are what a node
puts in [control] server_kem_pin and server_verify_pin. Both are required:
karst-control-v1.md §9 explains why a node given only the first loses forward
secrecy rather than failing.

Nodes also need the relay's certificate, since it is self-signed:

    $state/tls/relay.crt   ->  [control] relay_ca_file

And an enrollment key. The server mints one on first boot, because a setup key
would otherwise need an account and an account would need an identity provider:

    $state/bootstrap.key   ->  [control] setup_key

It is reusable and does not expire. Revoke it from the console once
authentication works — GETTING-STARTED.md §8.1.

EOF
