// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright the Karst contributors.

// Package karstapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package karstapi

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AuditSinkKind.
const (
	AuditSinkKindSyslog  AuditSinkKind = "syslog"
	AuditSinkKindWebhook AuditSinkKind = "webhook"
)

// Valid indicates whether the value is a known member of the AuditSinkKind enum.
func (e AuditSinkKind) Valid() bool {
	switch e {
	case AuditSinkKindSyslog:
		return true
	case AuditSinkKindWebhook:
		return true
	default:
		return false
	}
}

// Defines values for AuditSinkWriteKind.
const (
	AuditSinkWriteKindSyslog  AuditSinkWriteKind = "syslog"
	AuditSinkWriteKindWebhook AuditSinkWriteKind = "webhook"
)

// Valid indicates whether the value is a known member of the AuditSinkWriteKind enum.
func (e AuditSinkWriteKind) Valid() bool {
	switch e {
	case AuditSinkWriteKindSyslog:
		return true
	case AuditSinkWriteKindWebhook:
		return true
	default:
		return false
	}
}

// Defines values for AuthorityStatus.
const (
	AuthorityStatusActive      AuthorityStatus = "active"
	AuthorityStatusRetired     AuthorityStatus = "retired"
	AuthorityStatusUnavailable AuthorityStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the AuthorityStatus enum.
func (e AuthorityStatus) Valid() bool {
	switch e {
	case AuthorityStatusActive:
		return true
	case AuthorityStatusRetired:
		return true
	case AuthorityStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for BedrockModeWriteMode.
const (
	BedrockModeWriteModeAdvisory  BedrockModeWriteMode = "advisory"
	BedrockModeWriteModeEnforcing BedrockModeWriteMode = "enforcing"
	BedrockModeWriteModeOff       BedrockModeWriteMode = "off"
)

// Valid indicates whether the value is a known member of the BedrockModeWriteMode enum.
func (e BedrockModeWriteMode) Valid() bool {
	switch e {
	case BedrockModeWriteModeAdvisory:
		return true
	case BedrockModeWriteModeEnforcing:
		return true
	case BedrockModeWriteModeOff:
		return true
	default:
		return false
	}
}

// Defines values for BedrockStatusMode.
const (
	BedrockStatusModeAdvisory  BedrockStatusMode = "advisory"
	BedrockStatusModeEnforcing BedrockStatusMode = "enforcing"
	BedrockStatusModeOff       BedrockStatusMode = "off"
)

// Valid indicates whether the value is a known member of the BedrockStatusMode enum.
func (e BedrockStatusMode) Valid() bool {
	switch e {
	case BedrockStatusModeAdvisory:
		return true
	case BedrockStatusModeEnforcing:
		return true
	case BedrockStatusModeOff:
		return true
	default:
		return false
	}
}

// Defines values for DiagnosticSeverity.
const (
	DiagnosticSeverityError   DiagnosticSeverity = "error"
	DiagnosticSeverityWarning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case DiagnosticSeverityError:
		return true
	case DiagnosticSeverityWarning:
		return true
	default:
		return false
	}
}

// Defines values for NodePostureStatus.
const (
	NodePostureStatusLatticeOnly NodePostureStatus = "lattice_only"
	NodePostureStatusPq          NodePostureStatus = "pq"
	NodePostureStatusStale       NodePostureStatus = "stale"
	NodePostureStatusUnknown     NodePostureStatus = "unknown"
)

// Valid indicates whether the value is a known member of the NodePostureStatus enum.
func (e NodePostureStatus) Valid() bool {
	switch e {
	case NodePostureStatusLatticeOnly:
		return true
	case NodePostureStatusPq:
		return true
	case NodePostureStatusStale:
		return true
	case NodePostureStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for PathObservationKind.
const (
	PathObservationKindDirect      PathObservationKind = "direct"
	PathObservationKindRelay       PathObservationKind = "relay"
	PathObservationKindUnreachable PathObservationKind = "unreachable"
)

// Valid indicates whether the value is a known member of the PathObservationKind enum.
func (e PathObservationKind) Valid() bool {
	switch e {
	case PathObservationKindDirect:
		return true
	case PathObservationKindRelay:
		return true
	case PathObservationKindUnreachable:
		return true
	default:
		return false
	}
}

// Defines values for RelayHealthAdmissionState.
const (
	RelayHealthAdmissionStateConfirmed RelayHealthAdmissionState = "confirmed"
	RelayHealthAdmissionStateStale     RelayHealthAdmissionState = "stale"
	RelayHealthAdmissionStateUnknown   RelayHealthAdmissionState = "unknown"
)

// Valid indicates whether the value is a known member of the RelayHealthAdmissionState enum.
func (e RelayHealthAdmissionState) Valid() bool {
	switch e {
	case RelayHealthAdmissionStateConfirmed:
		return true
	case RelayHealthAdmissionStateStale:
		return true
	case RelayHealthAdmissionStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for RelayHealthSource.
const (
	RelayHealthSourceRosterMtime RelayHealthSource = "roster_mtime"
)

// Valid indicates whether the value is a known member of the RelayHealthSource enum.
func (e RelayHealthSource) Valid() bool {
	switch e {
	case RelayHealthSourceRosterMtime:
		return true
	default:
		return false
	}
}

// Defines values for SessionPostureStatus.
const (
	SessionPostureStatusLatticeOnly SessionPostureStatus = "lattice_only"
	SessionPostureStatusPq          SessionPostureStatus = "pq"
	SessionPostureStatusStale       SessionPostureStatus = "stale"
	SessionPostureStatusUnknown     SessionPostureStatus = "unknown"
)

// Valid indicates whether the value is a known member of the SessionPostureStatus enum.
func (e SessionPostureStatus) Valid() bool {
	switch e {
	case SessionPostureStatusLatticeOnly:
		return true
	case SessionPostureStatusPq:
		return true
	case SessionPostureStatusStale:
		return true
	case SessionPostureStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for Coverage.
const (
	CoverageCovered   Coverage = "covered"
	CoverageStale     Coverage = "stale"
	CoverageUncovered Coverage = "uncovered"
)

// Valid indicates whether the value is a known member of the Coverage enum.
func (e Coverage) Valid() bool {
	switch e {
	case CoverageCovered:
		return true
	case CoverageStale:
		return true
	case CoverageUncovered:
		return true
	default:
		return false
	}
}

// Defines values for ExportFormat.
const (
	ExportFormatCsv  ExportFormat = "csv"
	ExportFormatJson ExportFormat = "json"
)

// Valid indicates whether the value is a known member of the ExportFormat enum.
func (e ExportFormat) Valid() bool {
	switch e {
	case ExportFormatCsv:
		return true
	case ExportFormatJson:
		return true
	default:
		return false
	}
}

// Defines values for Posture.
const (
	PostureLatticeOnly Posture = "lattice_only"
	PosturePq          Posture = "pq"
	PostureStale       Posture = "stale"
	PostureUnknown     Posture = "unknown"
)

// Valid indicates whether the value is a known member of the Posture enum.
func (e Posture) Valid() bool {
	switch e {
	case PostureLatticeOnly:
		return true
	case PosturePq:
		return true
	case PostureStale:
		return true
	case PostureUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ExportAuditParamsFormat.
const (
	ExportAuditParamsFormatCsv  ExportAuditParamsFormat = "csv"
	ExportAuditParamsFormatJson ExportAuditParamsFormat = "json"
)

// Valid indicates whether the value is a known member of the ExportAuditParamsFormat enum.
func (e ExportAuditParamsFormat) Valid() bool {
	switch e {
	case ExportAuditParamsFormatCsv:
		return true
	case ExportAuditParamsFormatJson:
		return true
	default:
		return false
	}
}

// Defines values for ListNodesParamsPosture.
const (
	ListNodesParamsPostureLatticeOnly ListNodesParamsPosture = "lattice_only"
	ListNodesParamsPosturePq          ListNodesParamsPosture = "pq"
	ListNodesParamsPostureStale       ListNodesParamsPosture = "stale"
	ListNodesParamsPostureUnknown     ListNodesParamsPosture = "unknown"
)

// Valid indicates whether the value is a known member of the ListNodesParamsPosture enum.
func (e ListNodesParamsPosture) Valid() bool {
	switch e {
	case ListNodesParamsPostureLatticeOnly:
		return true
	case ListNodesParamsPosturePq:
		return true
	case ListNodesParamsPostureStale:
		return true
	case ListNodesParamsPostureUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ListNodesParamsCoverage.
const (
	ListNodesParamsCoverageCovered   ListNodesParamsCoverage = "covered"
	ListNodesParamsCoverageStale     ListNodesParamsCoverage = "stale"
	ListNodesParamsCoverageUncovered ListNodesParamsCoverage = "uncovered"
)

// Valid indicates whether the value is a known member of the ListNodesParamsCoverage enum.
func (e ListNodesParamsCoverage) Valid() bool {
	switch e {
	case ListNodesParamsCoverageCovered:
		return true
	case ListNodesParamsCoverageStale:
		return true
	case ListNodesParamsCoverageUncovered:
		return true
	default:
		return false
	}
}

// Defines values for ListPostureSessionsParamsPosture.
const (
	ListPostureSessionsParamsPostureLatticeOnly ListPostureSessionsParamsPosture = "lattice_only"
	ListPostureSessionsParamsPosturePq          ListPostureSessionsParamsPosture = "pq"
	ListPostureSessionsParamsPostureStale       ListPostureSessionsParamsPosture = "stale"
	ListPostureSessionsParamsPostureUnknown     ListPostureSessionsParamsPosture = "unknown"
)

// Valid indicates whether the value is a known member of the ListPostureSessionsParamsPosture enum.
func (e ListPostureSessionsParamsPosture) Valid() bool {
	switch e {
	case ListPostureSessionsParamsPostureLatticeOnly:
		return true
	case ListPostureSessionsParamsPosturePq:
		return true
	case ListPostureSessionsParamsPostureStale:
		return true
	case ListPostureSessionsParamsPostureUnknown:
		return true
	default:
		return false
	}
}

// AccessExplanation defines model for AccessExplanation.
type AccessExplanation struct {
	ChangedAt   time.Time `json:"changed_at"`
	ChangedBy   string    `json:"changed_by"`
	Destination string    `json:"destination"`
	Group       string    `json:"group"`
	Rule        int       `json:"rule"`
}

// AcknowledgementMismatch defines model for AcknowledgementMismatch.
type AcknowledgementMismatch struct {
	Code                  string   `json:"code"`
	Message               string   `json:"message"`
	RequiredCutOffHandles []string `json:"required_cut_off_handles"`
}

// AuditAnchor defines model for AuditAnchor.
type AuditAnchor struct {
	EntriesSinceAnchor   int        `json:"entries_since_anchor"`
	LastAnchoredAt       *time.Time `json:"last_anchored_at,omitempty"`
	LastAnchoredSequence *int       `json:"last_anchored_sequence"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action       string    `json:"action"`
	Actor        string    `json:"actor"`
	CreatedAt    time.Time `json:"created_at"`
	Detail       *string   `json:"detail,omitempty"`
	Hash         string    `json:"hash"`
	PreviousHash string    `json:"previous_hash"`
	Sequence     int       `json:"sequence"`
	Target       string    `json:"target"`
}

// AuditHead defines model for AuditHead.
type AuditHead struct {
	Hash     string `json:"hash"`
	Sequence int    `json:"sequence"`
}

// AuditPage defines model for AuditPage.
type AuditPage struct {
	Anchor     AuditAnchor  `json:"anchor"`
	Items      []AuditEntry `json:"items"`
	NextCursor *string      `json:"next_cursor"`
}

// AuditSink defines model for AuditSink.
type AuditSink struct {
	Endpoint string        `json:"endpoint"`
	Id       *string       `json:"id,omitempty"`
	Kind     AuditSinkKind `json:"kind"`
}

// AuditSinkKind defines model for AuditSink.Kind.
type AuditSinkKind string

// AuditSinkWrite defines model for AuditSinkWrite.
type AuditSinkWrite struct {
	Endpoint string             `json:"endpoint"`
	Kind     AuditSinkWriteKind `json:"kind"`
}

// AuditSinkWriteKind defines model for AuditSinkWrite.Kind.
type AuditSinkWriteKind string

// Authority defines model for Authority.
type Authority struct {
	Id     string          `json:"id"`
	Name   string          `json:"name"`
	Status AuthorityStatus `json:"status"`
}

// AuthorityStatus defines model for Authority.Status.
type AuthorityStatus string

// BedrockBootstrapBundle defines model for BedrockBootstrapBundle.
type BedrockBootstrapBundle struct {
	Format  string `json:"format"`
	Payload []byte `json:"payload"`
}

// BedrockLogEntry defines model for BedrockLogEntry.
type BedrockLogEntry struct {
	CreatedAt time.Time `json:"created_at"`
	Hash      string    `json:"hash"`
	Sequence  int       `json:"sequence"`
	Verified  bool      `json:"verified"`
}

// BedrockLogPage defines model for BedrockLogPage.
type BedrockLogPage struct {
	Items      []BedrockLogEntry `json:"items"`
	NextCursor *string           `json:"next_cursor"`
}

// BedrockModeWrite defines model for BedrockModeWrite.
type BedrockModeWrite struct {
	AcknowledgedCutOffHandles []string             `json:"acknowledged_cut_off_handles"`
	Mode                      BedrockModeWriteMode `json:"mode"`
}

// BedrockModeWriteMode defines model for BedrockModeWrite.Mode.
type BedrockModeWriteMode string

// BedrockStatus defines model for BedrockStatus.
type BedrockStatus struct {
	Authorities      []Authority       `json:"authorities"`
	CoveredCount     *int              `json:"covered_count,omitempty"`
	Disabled         *bool             `json:"disabled,omitempty"`
	Head             *string           `json:"head,omitempty"`
	HeadSeq          *int              `json:"head_seq,omitempty"`
	Mode             BedrockStatusMode `json:"mode"`
	Quorum           int               `json:"quorum"`
	Roots            []Authority       `json:"roots"`
	UncoveredHandles []string          `json:"uncovered_handles"`
	Zone             *string           `json:"zone,omitempty"`
}

// BedrockStatusMode defines model for BedrockStatus.Mode.
type BedrockStatusMode string

// ChainVerification defines model for ChainVerification.
type ChainVerification struct {
	FirstBadSequence *int      `json:"first_bad_sequence,omitempty"`
	Head             AuditHead `json:"head"`
	Reason           *string   `json:"reason,omitempty"`
	Valid            bool      `json:"valid"`
	Verified         *bool     `json:"verified,omitempty"`
}

// DeviceEnrolment defines model for DeviceEnrolment.
type DeviceEnrolment struct {
	ExpiresAt time.Time `json:"expires_at"`

	// Key Returned once when the one-use device key is created.
	Key *string `json:"key,omitempty"`
}

// DeviceRename defines model for DeviceRename.
type DeviceRename struct {
	Name string `json:"name"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Column   int                `json:"column"`
	Line     int                `json:"line"`
	Message  string             `json:"message"`
	Severity DiagnosticSeverity `json:"severity"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// Error defines model for Error.
type Error struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"request_id,omitempty"`
}

// Flow defines model for Flow.
type Flow struct {
	Destination string `json:"destination"`
	Ports       string `json:"ports"`
	Protocol    string `json:"protocol"`
	Source      string `json:"source"`
}

// MyDevice defines model for MyDevice.
type MyDevice struct {
	Handle     string     `json:"handle"`
	LastSeenAt *time.Time `json:"last_seen_at"`
	Name       string     `json:"name"`
	Platform   string     `json:"platform"`
}

// MySession defines model for MySession.
type MySession struct {
	Device    string     `json:"device"`
	EndedAt   *time.Time `json:"ended_at,omitempty"`
	Ip        *string    `json:"ip,omitempty"`
	StartedAt time.Time  `json:"started_at"`
}

// Node defines model for Node.
type Node struct {
	CreatedAt  time.Time   `json:"created_at"`
	Enabled    bool        `json:"enabled"`
	ExpiresAt  *time.Time  `json:"expires_at,omitempty"`
	Handle     *string     `json:"handle,omitempty"`
	LastSeenAt *time.Time  `json:"last_seen_at,omitempty"`
	Name       string      `json:"name"`
	Platform   string      `json:"platform"`
	Posture    NodePosture `json:"posture"`
	Tags       []string    `json:"tags"`
	UserId     string      `json:"user_id"`
}

// NodePage defines model for NodePage.
type NodePage struct {
	Items      []Node  `json:"items"`
	NextCursor *string `json:"next_cursor"`
}

// NodePaths defines model for NodePaths.
type NodePaths struct {
	ObservedAt *time.Time        `json:"observed_at"`
	Paths      []PathObservation `json:"paths"`
}

// NodePosture defines model for NodePosture.
type NodePosture struct {
	LatticeOnly *bool             `json:"lattice_only,omitempty"`
	ObservedAt  *time.Time        `json:"observed_at"`
	PskEpoch    *int              `json:"psk_epoch,omitempty"`
	Status      NodePostureStatus `json:"status"`
	Suite       *string           `json:"suite,omitempty"`
}

// NodePostureStatus defines model for NodePosture.Status.
type NodePostureStatus string

// NodeUpdate defines model for NodeUpdate.
type NodeUpdate struct {
	Enabled   *bool      `json:"enabled,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Tags      *[]string  `json:"tags,omitempty"`
}

// Page defines model for Page.
type Page struct {
	NextCursor *string `json:"next_cursor"`
}

// PathObservation defines model for PathObservation.
type PathObservation struct {
	Endpoint   *string             `json:"endpoint,omitempty"`
	Kind       PathObservationKind `json:"kind"`
	ObservedAt time.Time           `json:"observed_at"`
	PeerHandle string              `json:"peer_handle"`
	RelayId    *string             `json:"relay_id,omitempty"`
	Since      *time.Time          `json:"since,omitempty"`
}

// PathObservationKind defines model for PathObservation.Kind.
type PathObservationKind string

// PolicyPreview defines model for PolicyPreview.
type PolicyPreview struct {
	Added   []Flow `json:"added"`
	Removed []Flow `json:"removed"`
}

// PolicyTestResult defines model for PolicyTestResult.
type PolicyTestResult struct {
	Passed  bool `json:"passed"`
	Results []struct {
		Message *string `json:"message,omitempty"`
		Name    string  `json:"name"`
		Passed  bool    `json:"passed"`
	} `json:"results"`
}

// PolicyValidation defines model for PolicyValidation.
type PolicyValidation struct {
	Diagnostics []Diagnostic `json:"diagnostics"`
	Valid       bool         `json:"valid"`
}

// PolicyVersion defines model for PolicyVersion.
type PolicyVersion struct {
	Author    string    `json:"author"`
	CreatedAt time.Time `json:"created_at"`
	Document  string    `json:"document"`
	Version   int       `json:"version"`
}

// PolicyVersionPage defines model for PolicyVersionPage.
type PolicyVersionPage struct {
	Items      []PolicyVersion `json:"items"`
	NextCursor *string         `json:"next_cursor"`
}

// PolicyWrite defines model for PolicyWrite.
type PolicyWrite struct {
	// Document HuJSON policy document.
	Document string `json:"document"`
}

// PostureAggregate defines model for PostureAggregate.
type PostureAggregate struct {
	AsOf                time.Time      `json:"as_of"`
	EligibleSessions    int            `json:"eligible_sessions"`
	LatticeOnlySessions int            `json:"lattice_only_sessions"`
	ObservedSessions    int            `json:"observed_sessions"`
	PqCoveredSessions   int            `json:"pq_covered_sessions"`
	StaleNodes          int            `json:"stale_nodes"`
	Suites              map[string]int `json:"suites"`
	WindowStart         time.Time      `json:"window_start"`
}

// Relay defines model for Relay.
type Relay struct {
	Address string      `json:"address"`
	Health  RelayHealth `json:"health"`

	// Id Derived from identity_key; never accepted from callers.
	Id            *string `json:"id,omitempty"`
	IdentityKey   []byte  `json:"identity_key"`
	Region        string  `json:"region"`
	TlsServerName *string `json:"tls_server_name,omitempty"`
}

// RelayCreate defines model for RelayCreate.
type RelayCreate struct {
	Address       string  `json:"address"`
	IdentityKey   []byte  `json:"identity_key"`
	Region        string  `json:"region"`
	TlsServerName *string `json:"tls_server_name,omitempty"`
}

// RelayHealth defines model for RelayHealth.
type RelayHealth struct {
	AdmissionState  RelayHealthAdmissionState `json:"admission_state"`
	Bytes           *int                      `json:"bytes,omitempty"`
	LastConfirmedAt *time.Time                `json:"last_confirmed_at"`
	Sessions        *int                      `json:"sessions,omitempty"`
	Source          RelayHealthSource         `json:"source"`
}

// RelayHealthAdmissionState defines model for RelayHealth.AdmissionState.
type RelayHealthAdmissionState string

// RelayHealthSource defines model for RelayHealth.Source.
type RelayHealthSource string

// SessionPage defines model for SessionPage.
type SessionPage struct {
	Items      []SessionPosture `json:"items"`
	NextCursor *string          `json:"next_cursor"`
}

// SessionPosture defines model for SessionPosture.
type SessionPosture struct {
	LatticeOnly bool                 `json:"lattice_only"`
	NodeHandle  string               `json:"node_handle"`
	ObservedAt  time.Time            `json:"observed_at"`
	PeerHandle  string               `json:"peer_handle"`
	PskEpoch    *int                 `json:"psk_epoch,omitempty"`
	Status      SessionPostureStatus `json:"status"`
	Suite       *string              `json:"suite,omitempty"`
}

// SessionPostureStatus defines model for SessionPosture.Status.
type SessionPostureStatus string

// SignedBundle defines model for SignedBundle.
type SignedBundle struct {
	Format  string `json:"format"`
	Payload []byte `json:"payload"`
}

// SigningRequest defines model for SigningRequest.
type SigningRequest struct {
	CreatedAt   time.Time `json:"created_at"`
	Id          string    `json:"id"`
	PayloadHash string    `json:"payload_hash"`
}

// Action defines model for action.
type Action = string

// Actor defines model for actor.
type Actor = string

// Coverage defines model for coverage.
type Coverage string

// Cursor defines model for cursor.
type Cursor = string

// ExportFormat defines model for exportFormat.
type ExportFormat string

// Handle defines model for handle.
type Handle = string

// IfMatch defines model for ifMatch.
type IfMatch = string

// Limit defines model for limit.
type Limit = int

// ObservedSince defines model for observedSince.
type ObservedSince = time.Time

// Posture defines model for posture.
type Posture string

// RelayId defines model for relayId.
type RelayId = string

// Tag defines model for tag.
type Tag = string

// User defines model for user.
type User = string

// Version defines model for version.
type Version = int

// ValidationError defines model for ValidationError.
type ValidationError = Error

// VersionConflict defines model for VersionConflict.
type VersionConflict = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAuditEntriesParams defines parameters for ListAuditEntries.
type ListAuditEntriesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Actor  *Actor  `form:"actor,omitempty" json:"actor,omitempty"`
	Action *Action `form:"action,omitempty" json:"action,omitempty"`
}

// ExportAuditParams defines parameters for ExportAudit.
type ExportAuditParams struct {
	Format ExportAuditParamsFormat `form:"format" json:"format"`
}

// ExportAuditParamsFormat defines parameters for ExportAudit.
type ExportAuditParamsFormat string

// ExportAudit200JSONResponseBody0 defines parameters for ExportAudit.
type ExportAudit200JSONResponseBody0 = []AuditEntry

// ExportAudit200JSONResponseBody1 defines parameters for ExportAudit.
type ExportAudit200JSONResponseBody1 = openapi_types.File

// ExportAudit200JSONResponseBody defines parameters for ExportAudit.
type ExportAudit200JSONResponseBody struct {
	union json.RawMessage
}

// ListBedrockLogParams defines parameters for ListBedrockLog.
type ListBedrockLogParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	Tag      *Tag                     `form:"tag,omitempty" json:"tag,omitempty"`
	User     *User                    `form:"user,omitempty" json:"user,omitempty"`
	Posture  *ListNodesParamsPosture  `form:"posture,omitempty" json:"posture,omitempty"`
	Coverage *ListNodesParamsCoverage `form:"coverage,omitempty" json:"coverage,omitempty"`
	Cursor   *Cursor                  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *Limit                   `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListNodesParamsPosture defines parameters for ListNodes.
type ListNodesParamsPosture string

// ListNodesParamsCoverage defines parameters for ListNodes.
type ListNodesParamsCoverage string

// WritePolicyParams defines parameters for WritePolicy.
type WritePolicyParams struct {
	// IfMatch Current policy version ETag.
	IfMatch IfMatch `json:"If-Match"`
}

// RollbackPolicyParams defines parameters for RollbackPolicy.
type RollbackPolicyParams struct {
	// IfMatch Current policy version ETag.
	IfMatch IfMatch `json:"If-Match"`
}

// ListPolicyVersionsParams defines parameters for ListPolicyVersions.
type ListPolicyVersionsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPostureParams defines parameters for GetPosture.
type GetPostureParams struct {
	ObservedSince *ObservedSince `form:"observed_since,omitempty" json:"observed_since,omitempty"`
}

// ListPostureSessionsParams defines parameters for ListPostureSessions.
type ListPostureSessionsParams struct {
	Posture *ListPostureSessionsParamsPosture `form:"posture,omitempty" json:"posture,omitempty"`
	Cursor  *Cursor                           `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit   *Limit                            `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListPostureSessionsParamsPosture defines parameters for ListPostureSessions.
type ListPostureSessionsParamsPosture string

// CreateAuditSinkJSONRequestBody defines body for CreateAuditSink for application/json ContentType.
type CreateAuditSinkJSONRequestBody = AuditSinkWrite

// ImportBedrockBootstrapJSONRequestBody defines body for ImportBedrockBootstrap for application/json ContentType.
type ImportBedrockBootstrapJSONRequestBody = BedrockBootstrapBundle

// SetBedrockModeJSONRequestBody defines body for SetBedrockMode for application/json ContentType.
type SetBedrockModeJSONRequestBody = BedrockModeWrite

// ImportBedrockResponsesJSONRequestBody defines body for ImportBedrockResponses for application/json ContentType.
type ImportBedrockResponsesJSONRequestBody = SignedBundle

// RenameMyDeviceJSONRequestBody defines body for RenameMyDevice for application/json ContentType.
type RenameMyDeviceJSONRequestBody = DeviceRename

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody = NodeUpdate

// WritePolicyJSONRequestBody defines body for WritePolicy for application/json ContentType.
type WritePolicyJSONRequestBody = PolicyWrite

// PreviewPolicyJSONRequestBody defines body for PreviewPolicy for application/json ContentType.
type PreviewPolicyJSONRequestBody = PolicyWrite

// TestPolicyJSONRequestBody defines body for TestPolicy for application/json ContentType.
type TestPolicyJSONRequestBody = PolicyWrite

// ValidatePolicyJSONRequestBody defines body for ValidatePolicy for application/json ContentType.
type ValidatePolicyJSONRequestBody = PolicyWrite

// CreateRelayJSONRequestBody defines body for CreateRelay for application/json ContentType.
type CreateRelayJSONRequestBody = RelayCreate

// AsExportAudit200JSONResponseBody0 returns the union data inside the ExportAudit200JSONResponseBody as a ExportAudit200JSONResponseBody0
func (t ExportAudit200JSONResponseBody) AsExportAudit200JSONResponseBody0() (ExportAudit200JSONResponseBody0, error) {
	var body ExportAudit200JSONResponseBody0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExportAudit200JSONResponseBody0 overwrites any union data inside the ExportAudit200JSONResponseBody as the provided ExportAudit200JSONResponseBody0
func (t *ExportAudit200JSONResponseBody) FromExportAudit200JSONResponseBody0(v ExportAudit200JSONResponseBody0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExportAudit200JSONResponseBody0 performs a merge with any union data inside the ExportAudit200JSONResponseBody, using the provided ExportAudit200JSONResponseBody0
func (t *ExportAudit200JSONResponseBody) MergeExportAudit200JSONResponseBody0(v ExportAudit200JSONResponseBody0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsExportAudit200JSONResponseBody1 returns the union data inside the ExportAudit200JSONResponseBody as a ExportAudit200JSONResponseBody1
func (t ExportAudit200JSONResponseBody) AsExportAudit200JSONResponseBody1() (ExportAudit200JSONResponseBody1, error) {
	var body ExportAudit200JSONResponseBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromExportAudit200JSONResponseBody1 overwrites any union data inside the ExportAudit200JSONResponseBody as the provided ExportAudit200JSONResponseBody1
func (t *ExportAudit200JSONResponseBody) FromExportAudit200JSONResponseBody1(v ExportAudit200JSONResponseBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeExportAudit200JSONResponseBody1 performs a merge with any union data inside the ExportAudit200JSONResponseBody, using the provided ExportAudit200JSONResponseBody1
func (t *ExportAudit200JSONResponseBody) MergeExportAudit200JSONResponseBody1(v ExportAudit200JSONResponseBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ExportAudit200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ExportAudit200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
